zerocracy/farm

src/main/resources/com/zerocracy/stk/pm/scope/wbs/add_label_to_github_ticket.groovy, src/test/resources/com/zerocracy/bundles/adds_label_to_issue_in_wbs/_after.groovy, src/test/resources/com/zerocracy/bundles/adds_label_to_issue_in_wbs/_before.groovy, src/test/resources/com/zerocracy/bundles/adds_label_to_issue_in_wbs/claims.xml, src/test/resources/com/zerocracy/bundles/adds_label_to_issue_in_wbs/roles.xml
#403 
* Add "in" label to Github tasks in scope
* Added Bundles Test case
* Added puzzle for removing label on tasks out of scope
=> #403 Add "in" label to Github tasks in scope

src/main/java/com/zerocracy/tk/TkApp.java, src/main/java/com/zerocracy/tk/project/TkClaim.java, src/test/java/com/zerocracy/tk/project/TkClaimTest.java
#380 - take to render a claim from footprint
(from #441)
=> Claim take

src/main/resources/com/zerocracy/stk/pm/publish_project.groovy
#404: New projects being published will now be tweeted.
=> #404 Tweet when a project is published

src/main/xsl/gang.xsl
https://github.com/zerocracy/farm/issues/502 - Sort reputation as number
=> Sort reputation as number

src/main/xsl/gang.xsl, src/main/xsl/identify.xsl, src/main/xsl/profile.xsl
After a recent update on socatar.com it's possible now to request the required image size.
=> Serve resized profile photos on gang and other pages

src/test/java/com/zerocracy/farm/S3ItemTest.java
#511 - reproduced `ClosedChannelException` in `S3Item`.
=> ClosedChannelException

pom.xml, src/main/java/com/zerocracy/entry/ExtMongo.java
This fixes running tests locally #589
=> Embedded MongoDB

src/main/resources/com/zerocracy/stk/pm/scope/wbs/add_job_to_wbs.groovy, src/test/resources/com/zerocracy/bundles/modifies_wbs/_after.groovy, src/test/resources/com/zerocracy/bundles/modifies_wbs/_before.groovy, src/test/resources/com/zerocracy/bundles/modifies_wbs/claims.xml, src/test/resources/com/zerocracy/bundles/modifies_wbs/roles.xml
=> pick up GitHub issue assignee on "scope in"

src/main/java/com/zerocracy/pmo/People.java, src/test/java/com/zerocracy/pmo/PeopleTest.java
=> no more than 16 students

src/main/java/com/zerocracy/pm/time/Milestones.java, src/main/java/com/zerocracy/radars/github/RbMilestone.java, src/test/java/com/zerocracy/pm/time/MilestonesTest.java, src/test/resources/com/zerocracy/bundles/add_milestone/_after.groovy, src/test/resources/com/zerocracy/bundles/add_milestone/_before.groovy, src/test/resources/com/zerocracy/bundles/add_milestone/claims.xml
=> Milestone script

src/main/java/com/zerocracy/pmo/People.java, src/main/java/com/zerocracy/tk/profile/TkProfile.java, src/main/xsl/profile.xsl, src/test/java/com/zerocracy/pmo/PeopleTest.java
#448 - show mentor and students on profile page
=> show mentor and students

pom.xml
#474 - enforce jacoco coverage
=> enforce jacoco coverage

src/main/java/com/zerocracy/radars/telegram/ReProfile.java
zerocracy/datum#188 - telegram bot commands parsing
=> Commands instead of words for telegram bot

src/test/resources/com/zerocracy/bundles/impediments/_after.groovy, src/test/resources/com/zerocracy/bundles/impediments/_before.groovy, src/test/resources/com/zerocracy/bundles/impediments/claims.xml, src/test/resources/com/zerocracy/bundles/impediments/orders.xml, src/test/resources/com/zerocracy/bundles/impediments/wbs.xml
#447 - impediments limit test and todo
(datum PR: zerocracy/datum#281)
=> impediments limit

src/main/resources/com/zerocracy/stk/pm/scope/wbs/add_label_to_github_ticket.groovy, src/main/resources/com/zerocracy/stk/pm/scope/wbs/remove_label_from_github_ticket.groovy, src/test/resources/com/zerocracy/bundles/adds_label_to_issue_in_wbs/_before.groovy, src/test/resources/com/zerocracy/bundles/adds_label_to_issue_in_wbs/claims.xml
#478 - remove 'scope' label when removed from WBS
=> remove label from github ticket

src/main/java/com/zerocracy/pm/staff/Bans.java, src/main/resources/com/zerocracy/stk/pm/staff/bans/ban_canceled_order.groovy, src/main/resources/com/zerocracy/stk/pm/staff/bans/ban_github_reporter.groovy, src/test/java/com/zerocracy/pm/staff/BansTest.java
=> Duplicated bans

src/main/resources/com/zerocracy/stk/pm/cost/pay_per_github_bug.groovy, src/test/resources/com/zerocracy/bundles/assigns_and_notifies_on_vacation/_after.groovy, src/test/resources/com/zerocracy/bundles/points_awarded_to_reporter_with_role/_after.groovy, src/test/resources/com/zerocracy/bundles/points_awarded_to_reporter_with_role/_before.groovy, src/test/resources/com/zerocracy/bundles/points_awarded_to_reporter_with_role/claims.xml, src/test/resources/com/zerocracy/bundles/points_awarded_to_reporter_with_role/roles.xml
zerocracy/datum#248 - reproduced and fixed behavior in https://github.com/zerocracy/datum/issues/248 bug
=> Pay to any Zerocracy user for bug reporting

src/main/resources/com/zerocracy/stk/pm/qa/complete_qa_review.groovy
=> QA reviews

src/main/java/com/zerocracy/entry/ExtTwitter.java, src/main/java/com/zerocracy/radars/github/RbTweet.java, src/main/java/com/zerocracy/radars/github/TkGithub.java, src/main/resources/com/zerocracy/stk/pm/tweet_about_new_publishing.groovy
=> Twitter API wrapper

src/main/java/com/zerocracy/radars/slack/ReProfile.java, src/main/java/com/zerocracy/radars/slack/SlackRadar.java
PR for #226 
0crat will now react to unaddressed Slack direct messages as well.
=> #226 Accept unaddressed Slack direct messages

src/main/java/com/zerocracy/radars/github/RbOnClose.java, src/main/resources/com/zerocracy/stk/pm/in/orders/close_job.groovy, src/test/java/com/zerocracy/radars/github/RbOnCloseTest.java, src/test/resources/com/zerocracy/bundles/close_the_job/_before.groovy
#616 - set `until` claim field to 15min for close claims from `RbOnClose` reaction.
=> RbOnClose claim delay

src/main/resources/com/zerocracy/stk/pmo/agenda/delete_stale_jobs.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_jobs/_after.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_jobs/_before.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_jobs/claims.xml, src/test/resources/com/zerocracy/bundles/delete_stale_jobs/people.xml
#496 - delete stale jobs test, stakeholder and todo
=> Delete stale jobs

src/test/resources/com/zerocracy/bundles/apply_to_a_project/_after.groovy, src/test/resources/com/zerocracy/bundles/apply_to_a_project/_before.groovy, src/test/resources/com/zerocracy/bundles/apply_to_a_project/_setup.xml, src/test/resources/com/zerocracy/bundles/apply_to_a_project/claims.xml, src/test/resources/com/zerocracy/bundles/apply_to_a_project/people.xml
#377 - added `apply_to_project` test to prove that bug is not reproducing
=> Apply test

src/main/resources/com/zerocracy/stk/pmo/agenda/delete_stale_jobs.groovy
=> Fixed todo pdd marker

src/main/resources/com/zerocracy/stk/pmo/awards/penalize_architect_for_boost.groovy, src/main/resources/com/zerocracy/stk/pmo/profile/breakup.groovy, src/test/resources/com/zerocracy/bundles/set_boost_factor/_after.groovy, src/test/resources/com/zerocracy/bundles/set_boost_factor/_before.groovy, src/test/resources/com/zerocracy/bundles/set_boost_factor/claims.xml
PR for #220 
The ARC is penalized 10 points if a boost claim authored by them is found. 
Bundle test ``set_boost_factor`` updated to also cover this functionality.
=> #220 Penalize arch for boosting

src/main/java/com/zerocracy/radars/github/RbOnBug.java, src/main/resources/com/zerocracy/stk/pm/scope/wbs/add_job_to_wbs.groovy, src/test/java/com/zerocracy/radars/github/RbOnBugTest.java
=> Duplicated 'in' claim from 'bug' label

src/main/java/com/zerocracy/entry/HeapDump.java, src/main/java/com/zerocracy/tk/TkDump.java
Fix for #400.
Added skeleton classes with relevant puzzles.
=> Upload HeapDump to S3

src/main/resources/com/zerocracy/stk/pm/scope/wbs/add_job_to_wbs.groovy, src/test/resources/com/zerocracy/bundles/small_pr_skip_wbs/_after.groovy, src/test/resources/com/zerocracy/bundles/small_pr_skip_wbs/_before.groovy, src/test/resources/com/zerocracy/bundles/small_pr_skip_wbs/claims.xml
#510 - check PR size in `Add job to WBS` claim for `REV` jobs. Tried to write bundle test, but found it impossible because of this bug: https://github.com/zerocracy/farm/issues/739
so I added a `@todo` for this test.
=> Skip CR for small PR

src/main/xsl/team.xsl
#501 - reputation colors legend
=> Reputation colors

src/main/java/com/zerocracy/pmo/Awards.java, src/main/resources/com/zerocracy/stk/pmo/awards/refresh_awards.groovy, src/test/resources/com/zerocracy/bundles/refresh_awards/_after.groovy, src/test/resources/com/zerocracy/bundles/refresh_awards/_before.groovy, src/test/resources/com/zerocracy/bundles/refresh_awards/_setup.xml, src/test/resources/com/zerocracy/bundles/refresh_awards/claims.xml, src/test/resources/com/zerocracy/bundles/refresh_awards/people.xml
#386 - remove awards which are older than 90 days
=> Remove old awards

src/main/java/com/zerocracy/pm/staff/ranks/RnkGithubBug.java, src/main/resources/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy, src/test/java/com/zerocracy/pm/staff/ranks/RnkGithubBugTest.java
#576 - give higher rank for Github tickets with bug label
=> Github bugs rank

src/main/java/com/zerocracy/radars/github/RbMilestone.java, src/main/java/com/zerocracy/radars/github/TkGithub.java, src/test/java/com/zerocracy/radars/github/RbMilestoneTest.java
#609 - milestone rebound in `TkGithub`
=> Milestone rebound

src/main/java/com/zerocracy/Xocument.java, src/main/java/com/zerocracy/pmo/Catalog.java, src/main/resources/com/zerocracy/stk/pm/bootstrap.groovy, src/test/java/com/zerocracy/pmo/CatalogTest.java
#546 - advisers in catalog + `@todo`
=> Project advisers

pom.xml, src/main/java/com/zerocracy/pmo/People.java, src/main/java/com/zerocracy/tk/TkGang.java, src/main/resources/com/zerocracy/stk/pmo/awards/update_reputation.groovy, src/main/resources/com/zerocracy/stk/pmo/profile/purchase_rfp.groovy, src/test/java/com/zerocracy/pmo/PeopleTest.java, src/test/resources/com/zerocracy/bundles/awards_points/_after.groovy
#552 - keep person reputation in `people.xml`
=> Person reputation

src/main/java/com/zerocracy/pm/staff/votes/VsSpeed.java, src/main/java/com/zerocracy/pmo/Speed.java, src/test/java/com/zerocracy/pm/staff/votes/VsSpeedTest.java
#566 - speed votes zero speed reproduced and fixed
=> Speed votes fix

src/main/java/com/zerocracy/pmo/Agenda.java
PR for #422 
Initial implementation begun in https://github.com/zerocracy/datum/pull/331. The puzzle reflects the ARC's suggestion from [here](https://github.com/zerocracy/farm/pull/784#issuecomment-372447596).
=> #422 Puzzle for continuing implementation

src/main/java/com/zerocracy/pmo/Rfps.java, src/main/resources/com/zerocracy/stk/pmo/rfps/remove_expired_rfps.groovy, src/test/resources/com/zerocracy/bundles/remove_expired_rfps/_after.groovy, src/test/resources/com/zerocracy/bundles/remove_expired_rfps/_before.groovy, src/test/resources/com/zerocracy/bundles/remove_expired_rfps/_setup.xml, src/test/resources/com/zerocracy/bundles/remove_expired_rfps/claims.xml, src/test/resources/com/zerocracy/bundles/remove_expired_rfps/rfps.xml
#574 - added stakeholder to remove expired RFPs
=> Remove expired RFP

src/main/resources/com/zerocracy/stk/pm/qa/complete_qa_review.groovy, src/main/resources/com/zerocracy/stk/pm/qa/start_qa_review.groovy, src/test/resources/com/zerocracy/bundles/add_qa_job_to_agenda/_after.groovy, src/test/resources/com/zerocracy/bundles/add_qa_job_to_agenda/_before.groovy, src/test/resources/com/zerocracy/bundles/add_qa_job_to_agenda/claims.xml, src/test/resources/com/zerocracy/bundles/add_qa_job_to_agenda/people.xml, src/test/resources/com/zerocracy/bundles/add_qa_job_to_agenda/roles.xml, src/test/resources/com/zerocracy/bundles/remove_qa_job_from_agenda/_after.groovy, src/test/resources/com/zerocracy/bundles/remove_qa_job_from_agenda/_before.groovy, src/test/resources/com/zerocracy/bundles/remove_qa_job_from_agenda/claims.xml, src/test/resources/com/zerocracy/bundles/remove_qa_job_from_agenda/people.xml, src/test/resources/com/zerocracy/bundles/remove_qa_job_from_agenda/roles.xml, src/test/resources/log4j.properties
#822:
* QA review task is added to Agenda
* Also removed when QA is completed
* Added tests for both scenarios
=> #822 Add QA review to Agenda and remove when QA is done

src/main/java/com/zerocracy/Par.java, src/test/java/com/zerocracy/ParTest.java, src/test/resources/com/zerocracy/bundles/notify_awards/_after.groovy
#523 - ignore code parts regex in `Par`
=> Ignore code parts

src/main/java/com/zerocracy/pmo/Debts.java, src/main/resources/com/zerocracy/stk/pmo/debts/pay_all_debts.groovy, src/test/java/com/zerocracy/pmo/DebtsTest.java
#696 - pay debts if it is older than `46.days` days
=> Pay debts older than 20 days

.travis.yml, .travis/run.sh
#716 - removed `set -e` from `.travis.yml`, it may cause strange behavior, see https://github.com/travis-ci/docs-travis-ci-com/issues/1672
Reproduced in #906
=> Fixed travis build

src/main/java/com/zerocracy/entry/Pings.java, src/main/resources/quartz.properties, src/test/java/com/zerocracy/entry/PingsITTest.java
#919 - starting quartz correctly, fixed `quartz.properties`, added IT-test
=> Quartz start issue

src/main/java/com/zerocracy/entry/ExtTelegram.java, src/main/java/com/zerocracy/radars/telegram/TmZerocrat.java, src/test/java/com/zerocracy/entry/ExtTelegramITCase.java
#528 - added telegram test case
=> Telegram IT case

src/main/java/com/zerocracy/farm/props/Props.java, src/main/java/com/zerocracy/farm/props/PropsFarm.java, src/main/java/com/zerocracy/farm/props/PropsItem.java, src/main/java/com/zerocracy/farm/props/PropsProject.java, src/main/java/com/zerocracy/farm/props/package-info.java
=> #600 JavaDocs for Props farm

src/main/java/com/zerocracy/pmo/Blanks.java, src/main/resources/com/zerocracy/stk/pm/in/orders/close_job.groovy, src/test/java/com/zerocracy/pmo/BlanksTest.java
#760 - add jobs to `blanks.xml`
=> Blank jobs

src/main/resources/com/zerocracy/stk/pm/bootstrap.groovy, src/test/resources/com/zerocracy/bundles/bootstraps_short_named_project/_after.groovy, src/test/resources/com/zerocracy/bundles/bootstraps_short_named_project/_before.groovy, src/test/resources/com/zerocracy/bundles/bootstraps_short_named_project/claims.xml
#754 - check title length in bootstrap
=> Avoid short titles in bootstrap

src/test/java/com/zerocracy/tk/project/TkClaimTest.java
#761 - added test for claim with one child and test for claim with many children
=> More claim tests

src/main/java/com/zerocracy/radars/slack/SlackRadar.java, src/test/java/com/zerocracy/radars/slack/SlackRadarTest.java, src/test/resources/com/zerocracy/radars/slack/slack-bot.json
#687 
* refactored `SlackRadar` to allow better testing
* added todo to add more tests
=> #687 added test for SlackRadar

src/main/java/com/zerocracy/pm/staff/votes/VsWorkload.java, src/main/java/com/zerocracy/pmo/Agenda.java, src/main/resources/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy, src/test/java/com/zerocracy/pmo/AgendaTest.java
#808 workload changes:
- added new constructor to `VsWorkload` to get votes for particular project
- added `Agenda.job(Project)` method to find jobs for project, updated test
- `@todo` to add unit-test for  `VsWorkload`
=> Workload for project

src/main/java/com/zerocracy/tk/RsPage.java, src/test/java/com/zerocracy/tk/profile/TkAgendaTest.java
#402 
* added html rendering for Firefox
* covered with agenda page test
=> #402 html rendering for firefox

src/main/java/com/zerocracy/pmo/banks/Bank.java, src/main/java/com/zerocracy/pmo/banks/Crypto.java, src/main/java/com/zerocracy/pmo/banks/FkBank.java, src/main/java/com/zerocracy/pmo/banks/Paypal.java, src/test/java/com/zerocracy/pmo/banks/FkBankTest.java, src/test/java/com/zerocracy/pmo/banks/package-info.java
Initial skeleton for #565:
* added FkBank class, that is supposed to store the details to the internal `xml` file
* added relevant puzzles to address leftovers
=> #565 - introduce FkBank skeleton

src/main/java/com/zerocracy/radars/viber/ReProfile.java, src/main/java/com/zerocracy/radars/viber/Reaction.java, src/main/java/com/zerocracy/radars/viber/TkViber.java, src/main/java/com/zerocracy/radars/viber/VbBot.java, src/main/java/com/zerocracy/radars/viber/VbEvent.java, src/main/java/com/zerocracy/radars/viber/VbPerson.java, src/main/java/com/zerocracy/radars/viber/VbToken.java, src/main/java/com/zerocracy/radars/viber/package-info.java
#939: Created basic framework for Viber radar. Added puzzles for further implementation.
=> #939 Skeleton for Viber radar

src/main/java/com/zerocracy/pmo/banks/Payroll.java, src/main/java/com/zerocracy/pmo/banks/Zold.java, src/main/resources/com/zerocracy/radars/q-profile.xml
#1074 - allow to setup zold-wallets for users, add `ZoldBank` with `@todo` to implement.
=> Zold payments

pom.xml, src/main/java/com/zerocracy/pmo/People.java, src/test/java/com/zerocracy/pmo/PeopleTest.java
#613 
* added tests for People
* updated the coverage ratios
* added todo to continue increasing the coverage
=> #613 added test for People

src/main/resources/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy
#1078 - Disabled `RnkEstimates` to fix election
=> Disabled RnkEstimates

src/main/xsl/project.xsl
Let's add this button to the project page, for convenience.
=> add contrib button

src/main/java/com/zerocracy/entry/HeapDump.java, src/test/java/com/zerocracy/entry/HeapDumpTest.java
#768: Implement `HeapDump.save` functionality. Added `HeapDumpTest` and added related tests there.
=> #768 Implement HeapDump.save

src/main/java/com/zerocracy/Project.java, src/main/java/com/zerocracy/cash/ApiLayerQuotes.java, src/main/java/com/zerocracy/entry/Pings.java, src/main/java/com/zerocracy/pmo/Blanks.java, src/main/java/com/zerocracy/pmo/Debts.java, src/main/java/com/zerocracy/pmo/Pmo.java, src/main/java/com/zerocracy/pmo/Rfps.java, src/main/java/com/zerocracy/pmo/Speed.java, src/main/java/com/zerocracy/radars/github/Rebound.java, src/main/java/com/zerocracy/tk/rfp/TkRfp.java
#1126 - added javadocs for some classes
=> More javadocs

src/main/java/com/zerocracy/tk/TkJoin.java, src/test/java/com/zerocracy/tk/TkJoinTest.java
#956 - check applied time on join + test
=> Check applied time on join

src/main/xsl/profile.xsl, src/test/java/com/zerocracy/tk/profile/TkProfileTest.java
#1080 
- added test to verify the source of the error (when user had a general rate set the error was thrown
- fixed by doing comparison with a string `0` not an integer one
=> #1080 fixed profile page in firefox

src/main/groovy/com/zerocracy/stk/pm/staff/milestones/update_precedences.groovy, src/main/java/com/zerocracy/pm/time/Precedences.java, src/test/java/com/zerocracy/pm/time/PrecedencesTest.java
PR for #185 
Added class Precedences and left puzzle for continuing with the stakeholder.
=> Precedences + PrecedencesTest and puzzle

src/main/groovy/com/zerocracy/stk/pmo/awards/check_automatic_vacation.groovy, src/main/java/com/zerocracy/pmo/Awards.java, src/test/resources/com/zerocracy/bundles/turn_on_vacation_for_too_many_negative_awards/_after.groovy, src/test/resources/com/zerocracy/bundles/turn_on_vacation_for_too_many_negative_awards/_before.groovy
#1036 
- added implementation for automatic vacation for 8 negative awards in last 16 days
=> #1036 added auto-vacation for negative awards

src/test/resources/com/zerocracy/bundles/assigns_performer_pr/_after.groovy, src/test/resources/com/zerocracy/bundles/assigns_performer_pr/_before.groovy, src/test/resources/com/zerocracy/bundles/assigns_performer_pr/claims.xml, src/test/resources/com/zerocracy/bundles/assigns_performer_pr/roles.xml
#1015 
- created test for isse with manual assignement of PRs
- added todo for implementation
=> #1015 created test for issue

src/main/java/com/zerocracy/pmo/Options.java, src/test/resources/com/zerocracy/bundles/elections_dont_exceed_max_jobs_option/_after.groovy, src/test/resources/com/zerocracy/bundles/elections_dont_exceed_max_jobs_option/_before.groovy, src/test/resources/com/zerocracy/bundles/elections_dont_exceed_max_jobs_option/claims.xml, src/test/resources/com/zerocracy/bundles/elections_dont_exceed_max_jobs_option/options/yegor256.xml, src/test/resources/com/zerocracy/bundles/elections_dont_exceed_max_jobs_option/roles.xml, src/test/resources/com/zerocracy/bundles/elections_dont_exceed_max_jobs_option/wbs.xml
#1035 
- split the todo into 3 separate todos
- created test for max jobs option (and todo for implementation)
=> #1035 added test for max jobs option

src/main/xsl/board.xsl, src/test/java/com/zerocracy/tk/TkBoardTest.java
#1084 
- fixed check in board.xsl for funds (the cause of the error)
- added tests to guard the fix
=> #1084 fixing board page in firefox

src/main/java/com/zerocracy/entry/Main.java, src/main/java/com/zerocracy/radars/gitlab/TkGitlab.java, src/main/java/com/zerocracy/radars/gitlab/package-info.java, src/test/java/com/zerocracy/radars/gitlab/TkGitlabTest.java, src/test/java/com/zerocracy/radars/gitlab/package-info.java
#1144 
Initial support for GitLab, created dummy webhook and added todos to do more implementation.
=> #1144 started GitLab integration

src/test/resources/com/zerocracy/bundles/dont_turn_on_vacation_for_too_many_negative_awards_if_there_are_positives/_after.groovy, src/test/resources/com/zerocracy/bundles/dont_turn_on_vacation_for_too_many_negative_awards_if_there_are_positives/_before.groovy, src/test/resources/com/zerocracy/bundles/dont_turn_on_vacation_for_too_many_negative_awards_if_there_are_positives/claims.xml, src/test/resources/com/zerocracy/bundles/dont_turn_on_vacation_for_too_many_negative_awards_if_there_are_positives/people.xml
#1173 
* added a check if there are any positive awards for the last 16 days - this should prevent of automatic vacation
* added test to cover that
=> #1173 fixing automatic vacation

src/main/java/com/zerocracy/tk/RsPage.java, src/test/java/com/zerocracy/farm/sync/SyncProjectTest.java, src/test/java/com/zerocracy/tk/TkBoardTest.java, src/test/java/com/zerocracy/tk/profile/TkAgendaTest.java, src/test/java/com/zerocracy/tk/profile/TkProfileTest.java
#1168 
Disabling Firefox Saxon transformations - might help with OOM
=> #1168 disabling firefox transformation

src/main/java/com/zerocracy/tk/RsPage.java, src/test/java/com/zerocracy/tk/TkBoardTest.java, src/test/java/com/zerocracy/tk/profile/TkAgendaTest.java, src/test/java/com/zerocracy/tk/profile/TkProfileTest.java
#1168
* reverting changes for firefox
=> #1168 reverting firefox change

pom.xml, src/main/java/com/zerocracy/pm/Claims.java, src/test/java/com/zerocracy/pmo/PeopleTest.java
#1059 
- added links test for People (all other methods are already tested)
- removed People exclusion from jacoco
- removed todo
=> #1059 added test for People

src/main/groovy/com/zerocracy/stk/pm/in/links/terminate_orders_wbs_on_link_removal.groovy, src/main/java/com/zerocracy/pm/Claims.java, src/test/resources/com/zerocracy/bundles.terminates_orders_wbs_on_link_removal/_after.groovy, src/test/resources/com/zerocracy/bundles.terminates_orders_wbs_on_link_removal/_before.groovy, src/test/resources/com/zerocracy/bundles.terminates_orders_wbs_on_link_removal/claims.xml, src/test/resources/com/zerocracy/bundles.terminates_orders_wbs_on_link_removal/orders.xml, src/test/resources/com/zerocracy/bundles.terminates_orders_wbs_on_link_removal/roles.xml, src/test/resources/com/zerocracy/bundles.terminates_orders_wbs_on_link_removal/wbs.xml
#1055 
- added test for termination of orders/WBS in case github link is removed
- added todo for implementation
=> #1055 added test for termination of orders/wbs

src/main/java/com/zerocracy/pm/Claims.java, src/test/java/com/zerocracy/radars/slack/SlackRadarTest.java, src/test/resources/com/zerocracy/radars/slack/slack-bot2.json
#1060 
* added test for slack radar
=> #1060 added test for slack radar

pom.xml
=> Windows build fix

src/main/groovy/com/zerocracy/stk/pm/qa/complete_qa_review.groovy, src/main/groovy/com/zerocracy/stk/pm/qa/start_qa_review.groovy, src/main/groovy/com/zerocracy/stk/pmo/agenda/remove_from_agenda.groovy, src/main/java/com/zerocracy/Xocument.java, src/main/java/com/zerocracy/farm/fake/FkProject.java, src/main/java/com/zerocracy/pmo/Agenda.java, src/main/java/com/zerocracy/pmo/People.java, src/test/java/com/zerocracy/pmo/AgendaTest.java, src/test/resources/com/zerocracy/bundles/assign_qa_user/_after.groovy, src/test/resources/com/zerocracy/bundles/assign_qa_user/_before.groovy, src/test/resources/com/zerocracy/bundles/assign_qa_user/claims.xml, src/test/resources/com/zerocracy/bundles/assign_qa_user/roles.xml
#911 - added inspector to performer's agenda, also fixed qa`assign_qa_user` test which was not working correctly.
=> Show inspecting jobs in agenda

src/main/groovy/com/zerocracy/stk/pmo/vacancies/remove_old_vacancies.groovy, src/main/java/com/zerocracy/pmo/Vacancies.java, src/test/java/com/zerocracy/pmo/VacanciesTest.java, src/test/resources/com/zerocracy/bundles/remove_old_vacancies/_after.groovy, src/test/resources/com/zerocracy/bundles/remove_old_vacancies/_before.groovy, src/test/resources/com/zerocracy/bundles/remove_old_vacancies/_setup.xml, src/test/resources/com/zerocracy/bundles/remove_old_vacancies/claims.xml, src/test/resources/com/zerocracy/bundles/remove_old_vacancies/vacancies.xml
=> Remove old vacancies

src/main/java/com/zerocracy/pm/cost/Estimates.java
#1236 - estimates documentation
=> Documented estimates

src/test/java/com/zerocracy/tk/profile/TkAgendaTest.java, src/test/java/com/zerocracy/tk/profile/TkAwardsTest.java
#1063 
* added test for Firefox and awards page
=> #1063 added test for awards page

src/main/groovy/com/zerocracy/stk/pm/in/orders/finish_order.groovy, src/main/java/com/zerocracy/pm/qa/Reviews.java, src/test/resources/com/zerocracy/bundles/assign_qa_user/_after.groovy, src/test/resources/com/zerocracy/bundles/assign_qa_user/estimates.xml
#1175 - using estimates to calculate qa bonus
=> QA bonus calculation

src/main/java/com/zerocracy/pmo/People.java, src/test/java/com/zerocracy/pmo/PeopleTest.java
#1121: Added Jobs and Speed to `People.java`.
* Updated Datum to support new XML schema that includes `speed` element.
* Added `jobs` and `speed` to `People.java`
* Added tests
* Added puzzle for final implementation of speed.**
** Note: There is already an existing puzzle for adding jobs/agenda to `people.xml`. See #841.
=> #1121 Added Jobs, Speed to People

src/main/java/com/zerocracy/tk/RqUser.java, src/main/java/com/zerocracy/tk/profile/RqLogin.java, src/main/java/com/zerocracy/tk/profile/TkProfile.java, src/test/java/com/zerocracy/tk/RqWithUser.java, src/test/java/com/zerocracy/tk/profile/TkProfileTest.java
#1054 
* updated TkProfile (and RqLogin and RqUser) so PO can see the profile page and project links on it
* added todo for refactoring
* added test validating the behavior
=> #1054 PO can see profile page

src/main/groovy/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy, src/main/java/com/zerocracy/pm/staff/votes/VsBalance.java, src/test/java/com/zerocracy/pm/staff/votes/VsBalanceTest.java
#1174 
* added balance voter with tests
* using it in elections with `1` weight (@g4s8 should it be higher?)
=> #1174 added balance voter

src/main/java/com/zerocracy/pmo/Vacancies.java, src/main/java/com/zerocracy/tk/TkApp.java, src/main/java/com/zerocracy/tk/TkVacancies.java, src/main/resources/xsl/vacancies.xsl, src/test/java/com/zerocracy/pmo/VacanciesTest.java, src/test/java/com/zerocracy/tk/TkVacanciesTest.java
#970 - added vacancies `xsl` and `Take`
=> Vacancies page

src/test/java/com/zerocracy/tk/profile/TkAgendaTest.java, src/test/java/com/zerocracy/tk/profile/TkProfileTest.java
#1064 
- added test for Firefox rendering of profile page
=> #1064 added test for profile page

src/test/java/com/zerocracy/TxnTest.java
For #993: Added test which reveals NPE in Txn.acq().
=> For #993: Added test which reveals NPE in Txn.acq().

src/main/java/com/zerocracy/pm/staff/votes/VsWorkload.java, src/test/java/com/zerocracy/pm/staff/votes/VsWorkloadTest.java
#1061 
* added tests for VsWorkload
=> #1061 added tests for VsWorkload

src/main/java/com/zerocracy/pm/staff/votes/VsWorkload.java
#1061 
Forgot to remove todo in #1292
=> #1061 remove todo

src/main/groovy/com/zerocracy/stk/pm/cost/funding/contribute_by_stripe.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/send_zold.groovy, src/main/java/com/zerocracy/pmo/banks/Payroll.java, src/main/java/com/zerocracy/pmo/banks/Zold.java, src/main/resources/com/zerocracy/_props.xml
#1119 - implemented `Zold` payments, added stakeholder to send ZLD for contributing.
=> #1119 - zold payments

src/main/groovy/com/zerocracy/stk/package-info.java, src/main/groovy/com/zerocracy/stk/pmo/agenda/set_agenda_title_from_github.groovy, src/test/java/com/zerocracy/tk/profile/TkAgendaTest.java, src/test/resources/com/zerocracy/bundles/set_agenda_title_from_github/_after.groovy, src/test/resources/com/zerocracy/bundles/set_agenda_title_from_github/_before.groovy, src/test/resources/com/zerocracy/bundles/set_agenda_title_from_github/claims.xml
#1152 
- changed the claim for which set title stakeholder is listening (`Start order` makes more sense than a new claim type that is not sent by anyone)
- updated the test
- remove todo
=> #1152 set title in agenda

src/main/groovy/com/zerocracy/stk/pm/cost/funding/contribute_by_stripe.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/fund_by_stripe.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/send_zold.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/make_payment.groovy
#1291 - send extra zold on each payment
=> Extra zold payments

src/main/java/com/zerocracy/pmo/banks/FkBank.java, src/test/java/com/zerocracy/pmo/banks/FkBankTest.java
#1068 
Implemented equals and hashcode for FkBank.
=> #1068 implemented equals and hashcode

src/main/java/com/zerocracy/radars/viber/VbEvent.java, src/test/java/com/zerocracy/radars/viber/VbEventTest.java, src/test/java/com/zerocracy/radars/viber/package-info.java, src/test/resources/com/zerocracy/radars/viber/message.json
#1072 
* implemented VbEvent Simple and Message + tests
=> #1072 implemented VbEvent

src/main/java/com/zerocracy/pm/staff/votes/VsReputation.java, src/test/java/com/zerocracy/pm/staff/votes/VsReputationTest.java
#1129: Fixed `VsReputation`, users with higher reputation are now ranked higher. Also added (previously missing) unit test to verify correct behavior
=> #1129 Fixed VsReputation, added unit test

src/main/java/com/zerocracy/pmo/banks/FkBank.java, src/test/java/com/zerocracy/pmo/banks/FkBankTest.java
#1067 
* implemented FkBank.fee
=> #1067 implemented fee in Fake Bank

src/main/java/com/zerocracy/entry/Main.java, src/main/java/com/zerocracy/radars/viber/TkViber.java, src/main/java/com/zerocracy/radars/viber/VbBot.java, src/test/java/com/zerocracy/radars/viber/TkViberTest.java, src/test/java/com/zerocracy/radars/viber/package-info.java, src/test/resources/com/zerocracy/radars/viber/message.json
#1070
Implemented TkViber for receiving messages from Viber.
=> #1070 implemented TkViber

appveyor.yml, pom.xml, src/test/java/com/zerocracy/radars/github/RbPingArchitectTest.java
#1083 
- Created tests for RbPingArchitect
- updated new coverage values (branch 52%, classes missed 60)
- todo for continuation
=> #1083 increasing coverage in RbPingArchitect

src/main/groovy/com/zerocracy/stk/pmo/resumes/assign_examiner.groovy, src/main/java/com/zerocracy/pmo/Resumes.java, src/test/java/com/zerocracy/pmo/ResumesTest.java
#1146 - added stakeholder to assign resumes to examiners
=> Resumes stakeholder

src/main/groovy/com/zerocracy/stk/pm/in/orders/resign_on_delay.groovy, src/test/resources/com/zerocracy/bundles/resign_on_delay/_after.groovy, src/test/resources/com/zerocracy/bundles/resign_on_delay/_before.groovy, src/test/resources/com/zerocracy/bundles/resign_on_delay/claims.xml, src/test/resources/com/zerocracy/bundles/resign_on_delay/orders.xml, src/test/resources/com/zerocracy/bundles/resign_on_delay/roles.xml, src/test/resources/com/zerocracy/bundles/resign_on_delay/wbs.xml
#1302 - don't resign `REV` jobs by delay
=> Don't resign REV jobs

src/main/groovy/com/zerocracy/stk/pm/in/orders/update_verbosity.groovy, src/main/java/com/zerocracy/pmo/Agenda.java, src/test/java/com/zerocracy/pmo/AgendaTest.java
#1096 
Added git commit count to verbosity (end extended Agenda for that).
=> #1096 add git commits to verbosity

src/main/java/com/zerocracy/pmo/Speed.java, src/test/java/com/zerocracy/pmo/SpeedTest.java
PR for #860 
* Added ``int :: Speed.bonus(...)`` which returns the bonus, in minutes, for a completed job
* Added unit tests
* Left puzzle for continuing implementation in the payments stakeholder
=> #860 Speed.bonus(...) + unit test and puzzle

src/main/groovy/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy, src/main/java/com/zerocracy/pm/staff/votes/VsOverElected.java, src/test/java/com/zerocracy/pm/staff/votes/VsOverElectedTest.java
#926 - prevent over-election in one project added todo to synchonize multi-project election.
=> Prevent over-election

src/main/java/com/zerocracy/Xocument.java, src/main/java/com/zerocracy/pmo/People.java, src/test/java/com/zerocracy/pmo/PeopleTest.java, src/test/resources/com/zerocracy/bundles/refresh_person_job_count_on_agenda_update/people.xml
#1350 - zold wallets in `people.xml`
=> Zold wallets

src/test/java/com/zerocracy/tk/TkBoardTest.java, src/test/java/com/zerocracy/tk/View.java, src/test/java/com/zerocracy/tk/profile/TkAgendaTest.java, src/test/java/com/zerocracy/tk/profile/TkAwardsTest.java, src/test/java/com/zerocracy/tk/profile/TkProfileTest.java
#1142 
* Added `View` class with XML and HTML view of given zerocracy page
* Refactored test classes to use the new View class
=> #1142 added html/xml view class

src/main/java/com/zerocracy/pm/staff/votes/VsBalance.java
#1372 - added logs for balance votes
=> Log balance votes

src/main/groovy/com/zerocracy/stk/pmo/people/update_skills.groovy, src/main/java/com/zerocracy/pmo/People.java, src/main/java/com/zerocracy/tk/TkTeam.java, src/test/java/com/zerocracy/pmo/PeopleTest.java
#559 
* adding and listing skills for people
* todos to continue work
=> #559 adding skills to people

src/main/java/com/zerocracy/pmo/banks/FkBank.java, src/test/java/com/zerocracy/pmo/banks/PayrollTest.java
For #1069:
- Created `PayrollTest` to test `Payroll`
- Created test for amount too small payment;
- Added puzzles to test remaining `Payroll.pay` results;
- Updated puzzle.
=> #1069: Added test to Payroll.

README.md, src/main/groovy/com/zerocracy/stk/pm/comm/notify.groovy, src/main/groovy/com/zerocracy/stk/pm/comm/notify_all.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/contribute_by_stripe.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/donate_funds.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/fund_by_stripe.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/recharge_on_deficit.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/remember_stripe_charge.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/send_zold.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/stop_recharging.groovy
#1310 - added documentation for some stakeholders
=> Documentation for stakeholders

src/main/groovy/com/zerocracy/stk/pmo/people/remove_mentor_when_graduated.groovy, src/test/resources/com/zerocracy/bundles/graduation/_after.groovy, src/test/resources/com/zerocracy/bundles/graduation/_before.groovy, src/test/resources/com/zerocracy/bundles/graduation/_setup.xml, src/test/resources/com/zerocracy/bundles/graduation/claims.xml, src/test/resources/com/zerocracy/bundles/graduation/people.xml
#1242 - pay mentor on student graduation, added bundle test
=> Pay mentor on student graduation

pom.xml, src/main/groovy/com/zerocracy/stk/pm/comm/notify.groovy, src/main/java/com/zerocracy/entry/Main.java, src/main/java/com/zerocracy/radars/viber/TkViber.java, src/main/java/com/zerocracy/radars/viber/VbBot.java, src/main/resources/com/zerocracy/_props.xml, src/test/java/com/zerocracy/radars/viber/TkViberTest.java, src/test/java/com/zerocracy/radars/viber/VbBotTest.java
#1071: Implemented `VbBot.sendMessage`. Added unit test; added puzzle to allow notification via Viber.
=> #1071 Implement VbBot.sendMessage

src/test/java/com/zerocracy/SafeSentryTest.java
For #1442:
- Added synchronization to logger access;
- Changed Matchers.contains to Matchers.hasItem.
=> For #1442: SafeSentryTest.logsThrownException fails intermittently

src/main/java/com/zerocracy/pmo/Options.java
=> #1186 removing stale todo

src/main/groovy/com/zerocracy/stk/pmo/profile/change_vacation_mode.groovy, src/main/resources/com/zerocracy/radars/q-profile.xml, src/test/java/com/zerocracy/radars/QuestionTest.java, src/test/resources/com/zerocracy/bundles/checks_vacation_status/_after.groovy, src/test/resources/com/zerocracy/bundles/checks_vacation_status/_before.groovy, src/test/resources/com/zerocracy/bundles/checks_vacation_status/_setup.xml, src/test/resources/com/zerocracy/bundles/checks_vacation_status/claims.xml, src/test/resources/com/zerocracy/bundles/checks_vacation_status/people.xml
For #1210: /vacation shows vacation status:
- Added code for absent `mode` parameter in `change_vacation_mode.groovy`
- Added `optional` tag for `mode` parameter in `q-profile.xml`
- Created bundle test for asking vacation status.
=> For #1210: /vacation shows vacation status:

src/main/java/com/zerocracy/pm/ClaimsItem.java, src/test/java/com/zerocracy/pm/ClaimsItemTest.java
#1489 - do not add duplicate claims to `claims.xml`
=> Ignore duplicate claims

src/main/groovy/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy, src/test/resources/com/zerocracy/bundles/dont_assign_job_closed/_after.groovy, src/test/resources/com/zerocracy/bundles/dont_assign_job_closed/_before.groovy, src/test/resources/com/zerocracy/bundles/dont_assign_job_closed/claims.xml, src/test/resources/com/zerocracy/bundles/dont_assign_job_closed/roles.xml, src/test/resources/com/zerocracy/bundles/dont_assign_job_closed/wbs.xml
For #1214:
- Created tests assuring that `0crat` is assiging closed github issues ;
- Left puzzle for fixes.
=> For #1214: 0crat can assign closed bug

src/main/groovy/com/zerocracy/stk/pmo/awards/refresh_awards.groovy, src/test/resources/com/zerocracy/bundles/dont_refresh_awards_when_no_changes/_after.groovy, src/test/resources/com/zerocracy/bundles/dont_refresh_awards_when_no_changes/_before.groovy, src/test/resources/com/zerocracy/bundles/dont_refresh_awards_when_no_changes/_setup.xml, src/test/resources/com/zerocracy/bundles/dont_refresh_awards_when_no_changes/claims.xml, src/test/resources/com/zerocracy/bundles/dont_refresh_awards_when_no_changes/people.xml
For #1218:
- Added test reproducing submitting claim when reputation does not changes 
- Added todo for fixing this situation.
=> For #1218: refresh_awards can submit empty claims

src/main/groovy/com/zerocracy/stk/pm/in/orders/finish_order.groovy, src/test/resources/com/zerocracy/bundles/assign_qa_user/_after.groovy, src/test/resources/com/zerocracy/bundles/close_job_with_quality_review/_after.groovy, src/test/resources/com/zerocracy/bundles/close_job_with_quality_review/_before.groovy, src/test/resources/com/zerocracy/bundles/close_job_with_quality_review/claims.xml, src/test/resources/com/zerocracy/bundles/close_job_with_quality_review/wbs.xml
#1287 
* corrected REV bonus
* updated test to check the amounts
=> #1287 corrected REV bonus

src/main/groovy/com/zerocracy/stk/pmo/refresh_metrics.groovy, src/main/java/com/zerocracy/Xocument.java, src/main/java/com/zerocracy/pmo/Blanks.java, src/main/java/com/zerocracy/pmo/Speed.java, src/main/java/com/zerocracy/pmo/Verbosity.java, src/test/java/com/zerocracy/pm/staff/votes/VsSpeedTest.java, src/test/java/com/zerocracy/pmo/SpeedTest.java, src/test/resources/com/zerocracy/bundles/refresh_person_average_speed_on_speed_update/_before.groovy, src/test/resources/com/zerocracy/bundles/refresh_person_job_count_on_agenda_update/_after.groovy, src/test/resources/com/zerocracy/bundles/refresh_speed/_after.groovy, src/test/resources/com/zerocracy/bundles/refresh_speed/_before.groovy, src/test/resources/com/zerocracy/bundles/refresh_speed/claims.xml, src/test/resources/com/zerocracy/bundles/refresh_speed/pmo_people.xml
#1099 
* updated datum to 0.62.3
* fixed issues resulting from the upgrade (need for `added` in verbosity, speed and blanks)
* added cropping of speed to 90 days
=> #1099 crop speed of delivery

src/main/java/com/zerocracy/pmo/Verbosity.java, src/test/java/com/zerocracy/pmo/VerbosityTest.java
For #1233:
- Added test creating the condition to `Verbosity.add()` throw exception in `VerbosityTest`.
- Added puzzle for implementation of correction in `Verbosity`.
=> For #1233: Test for override verbosity.

src/test/java/com/zerocracy/TestListener.java
For #1227: Added javadoc about research work made in #1227.
=> For #1227: Added javadoc about ticket.

pom.xml
For #1231:
- Added `locale` values for `surefire` plugin
- Uncommented `excludes` for tests
- Left todo for `S3ItemTest`
=> For #1231: Fix error running tests in windows.

src/main/java/com/zerocracy/radars/slack/FkPersona.java, src/main/java/com/zerocracy/radars/slack/FkSkSession.java, src/main/java/com/zerocracy/radars/slack/FkTeam.java, src/test/resources/com/zerocracy/bundles/notify_in_slack_without_user/_before.groovy
For #1139: 
- Added `FkSkSession`, `FkPersona` and `FkTeam` classes
- Changed puzzle to continue `Mockito` removal.
=> For #1139: Add FkSkSession, FkPersona and FkTeam classes.

src/main/groovy/com/zerocracy/stk/pm/comm/notify_in_github.groovy, src/main/java/com/zerocracy/radars/github/AcceptInvitations.java, src/main/java/com/zerocracy/radars/github/Quota.java, src/main/java/com/zerocracy/radars/github/TkGithub.java, src/test/java/com/zerocracy/radars/github/AcceptInvitationsTest.java
#1390 
- generating log in AcceptInvitations
- adding testcase AcceptInvitationsTest
=> #1390 AcceptInvitations log warn when github quota is over

src/main/groovy/com/zerocracy/stk/internal/update_heapdump.groovy, src/main/java/com/zerocracy/farm/strict/StrictProject.java, src/test/resources/com/zerocracy/bundles/update_heapdump/_after.groovy, src/test/resources/com/zerocracy/bundles/update_heapdump/_before.groovy, src/test/resources/com/zerocracy/bundles/update_heapdump/_setup.xml, src/test/resources/com/zerocracy/bundles/update_heapdump/claims.xml
For #1232: 
- Created bundle tests for `update_heapdump.groovy`
- Changed `update_heapdump.groovy` for using `FkBucket()` when testing
=> For#1232: Implement update_heapdump tests

src/main/groovy/com/zerocracy/stk/pm/comm/notify_all.groovy, src/main/java/com/zerocracy/pmo/Options.java, src/main/java/com/zerocracy/tk/TkJoinPost.java, src/main/java/com/zerocracy/tk/project/TkHiring.java, src/main/java/com/zerocracy/tk/rfp/TkSubmit.java, src/test/java/com/zerocracy/pmo/OptionsTest.java, src/test/resources/com/zerocracy/bundles/respects_notification_options/_after.groovy, src/test/resources/com/zerocracy/bundles/respects_notification_options/_before.groovy, src/test/resources/com/zerocracy/bundles/respects_notification_options/_setup.xml, src/test/resources/com/zerocracy/bundles/respects_notification_options/claims.xml, src/test/resources/com/zerocracy/bundles/respects_notification_options/options/g4s8.xml, src/test/resources/com/zerocracy/bundles/respects_notification_options/options/paulodamaso.xml, src/test/resources/com/zerocracy/bundles/respects_notification_options/people.xml
#1185: Check user's notification options before notifying them of new RFPs, students, and projects.
=> #1185 Enable checking of notification options

src/test/resources/com/zerocracy/bundles/remove_from_agenda_on_repo_rename/_after.groovy, src/test/resources/com/zerocracy/bundles/remove_from_agenda_on_repo_rename/_before.groovy, src/test/resources/com/zerocracy/bundles/remove_from_agenda_on_repo_rename/_setup.xml, src/test/resources/com/zerocracy/bundles/remove_from_agenda_on_repo_rename/claims.xml, src/test/resources/com/zerocracy/bundles/remove_from_agenda_on_repo_rename/people.xml
For #1077: Added a test proving that jobs are removed from agenda on github repository rename.
=> #1077: Finished job not removed from agenda.

src/main/java/com/zerocracy/pm/staff/votes/VsBalance.java
VsBalance message looks like this right now:
```
Has 15 jobs in 5 projects, 0.60% from current project
```
After the change it will be:
```
Has 15 jobs in 5 projects, 60% from current project
```
=> Fix VsBalance message

src/main/groovy/com/zerocracy/stk/pmo/resumes/assign_examiner.groovy, src/test/resources/com/zerocracy/bundles/assign_examiner/_after.groovy, src/test/resources/com/zerocracy/bundles/assign_examiner/_before.groovy, src/test/resources/com/zerocracy/bundles/assign_examiner/_setup.xml, src/test/resources/com/zerocracy/bundles/assign_examiner/claims.xml, src/test/resources/com/zerocracy/bundles/assign_examiner/people.xml, src/test/resources/com/zerocracy/bundles/assign_examiner/roles.xml
For #1353:
- Added bundle test asserting that examiner is not on vacation and does not have reputation below minimum.
- Removed puzzle.
=> For #1353: assing_examiner.groovy tests.

.rultor.yml
#1104 
Added explicit locale with UTF for rultor - so tests can use UTF in assertions.
=> #1104 fix rultor config for UTF

src/main/java/com/zerocracy/Xocument.java
=> upgrade datum to 0.62.4

src/main/java/com/zerocracy/tk/RsParFlash.java, src/main/resources/xsl/layout.xsl, src/test/java/com/zerocracy/tk/View.java, src/test/java/com/zerocracy/tk/profile/TkProfileTest.java
#1104 
* created new template to display `flash` text (with disable-output-escaping=yes)
* added test to validate fix
* fixed RsParFlash
=> #1104 display link to policy for unknown user

.rultor.yml, src/main/java/com/zerocracy/pm/scope/Wbs.java, src/main/java/com/zerocracy/tk/TkApp.java, src/main/java/com/zerocracy/tk/profile/TkUserWbs.java, src/main/resources/xsl/inner-layout.xsl, src/test/java/com/zerocracy/tk/profile/TkUserWbsTest.java
#1159 
* created initial "User WBS" page - current one is a mock displaying only a list of user project pids
* added two todos to continue implementation
=> #1159 initial user wbs page

.rultor.yml, src/test/java/com/zerocracy/claims/proc/MessageMonitorProcTest.java
#1633 - reverted and fixed `MessageMonitorProcTest` test
=> MessageMonitorProcTest fix

src/main/groovy/com/zerocracy/stk/pm/cost/funding/send_zold.groovy, src/test/resources/com/zerocracy/bundles/send_correct_zold_value/_after.groovy, src/test/resources/com/zerocracy/bundles/send_correct_zold_value/_before.groovy, src/test/resources/com/zerocracy/bundles/send_correct_zold_value/claims.xml, src/test/resources/com/zerocracy/bundles/send_correct_zold_value/equity.xml, src/test/resources/com/zerocracy/bundles/send_correct_zold_value/people.xml, src/test/resources/com/zerocracy/bundles/send_correct_zold_value/roles.xml
For #1346: Make correct zold payment:
- Added bundle test for zold payment to user with vesting and user without vesting;
- Added puzzle to direct alterations in `send_zold.groovy`
=> For #1346: Make correct zold payment.

src/main/groovy/com/zerocracy/stk/pmo/awards/add_award_points.groovy, src/main/groovy/com/zerocracy/stk/pmo/profile/invite_friend.groovy, src/main/groovy/com/zerocracy/stk/pmo/resumes/assign_examiner.groovy, src/test/resources/com/zerocracy/bundles/examiner_can_invite/_after.groovy, src/test/resources/com/zerocracy/bundles/examiner_can_invite/claims.xml
#1552
* inviter will now get +32 points for inviting
* updated test for friend invitation
* changed user.json('type') and user.json('name') to correct user methods - now it will work correctly with MkUser
* added new type of message, to be able to award just points without payment
=> #1552 added bonus points for invitation

src/main/java/com/zerocracy/pmo/People.java, src/main/java/com/zerocracy/pmo/banks/Crypto.java, src/main/java/com/zerocracy/pmo/banks/Payroll.java, src/test/java/com/zerocracy/pmo/PeopleTest.java
#1304 - throw exception for not supported paymant methods
=> Drop ETH, BCH, LTC payments

src/main/groovy/com/zerocracy/stk/pm/cost/funding/send_zold.groovy, src/test/resources/com/zerocracy/bundles/send_correct_zold_value/_after.groovy, src/test/resources/com/zerocracy/bundles/send_correct_zold_value/_before.groovy, src/test/resources/com/zerocracy/bundles/send_correct_zold_value/claims.xml
For #1648:
- Corrected `send_zold.groovy` calculations
- Corrected test
=> For #1648: Correct send zold calculations.

pom.xml, src/main/groovy/com/zerocracy/stk/pm/cost/funding/recharge_on_deficit.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/recharge_project.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/remember_stripe_charge.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/stop_recharging.groovy, src/main/java/com/zerocracy/Xocument.java, src/main/java/com/zerocracy/claims/ClaimIn.java, src/main/java/com/zerocracy/claims/ClaimOut.java, src/main/java/com/zerocracy/claims/ClaimSignature.java, src/main/java/com/zerocracy/pmo/recharge/Recharge.java, src/main/java/com/zerocracy/tk/project/TkProject.java, src/test/java/com/zerocracy/claims/ClaimSignatureTest.java, src/test/java/com/zerocracy/pmo/recharge/RechargeTest.java
#1672 - add check `recharge.required` before recharging. Added unique signature source for all recharge claims in project, but keep claims flow.
=> Check recharge need before recharging

src/main/java/com/zerocracy/tk/TkTeam.java, src/main/resources/xsl/team.xsl, src/test/java/com/zerocracy/tk/TkTeamTest.java
#1332 
* added hiding of users that didn't receive any awards during the last 90 days
* added text informing about that on the team page
=> #1332 hide inactive users

src/main/groovy/com/zerocracy/stk/pm/scope/wbs/add_job_to_wbs.groovy, src/test/resources/com/zerocracy/bundles/small_pr_skip_wbs/_after.groovy, src/test/resources/com/zerocracy/bundles/small_pr_skip_wbs/_before.groovy, src/test/resources/com/zerocracy/bundles/small_pr_skip_wbs/claims.xml
For #770: Do not add small pull requests to WBS:
- Corrected `add_job_to_wbs.groovy`
- Added tests
=> For #770: Do not add small pull requests to WBS.

src/main/groovy/com/zerocracy/stk/pmo/profile/deny_resume.groovy, src/main/groovy/com/zerocracy/stk/pmo/resumes/assign_examiner.groovy, src/main/java/com/zerocracy/pmo/Resumes.java, src/main/resources/com/zerocracy/radars/q-profile.xml, src/test/resources/com/zerocracy/bundles/deny_resume_application/_after.groovy
#1666 
* added `deny @login` option
* enabled test
* added stakeholder for denying
=> #1666 added ability to deny resume

src/main/groovy/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy, src/main/java/com/zerocracy/pm/staff/ranks/RnkGithubLabel.java, src/test/java/com/zerocracy/pm/staff/ranks/RnkGithubLabelTest.java
#1211 
* refactored GithubBug, to be general label rank
* added ranking for `pdd` label
=> #1211 added ranking for pdd

pom.xml, src/main/java/com/zerocracy/Xocument.java, upgrade_bundles.groovy
#1705 
* created upgrade_bundles profile (with two needed dependencies)
* added todo to fix the upgaded xml files to comply with xcop (without it each build will fail)
=> #1705 added upgrade-bundles profile

src/main/groovy/com/zerocracy/stk/pmo/agenda/delete_stale_jobs.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_jobs/_after.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_jobs/_before.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_jobs/people.xml
#1341 
* added exclusion for removal of agenda tests that are under review (have inspector)
* added test for checking that agenda items under review are not removed
=> #1341 dont remove agenda jobs that are under review

src/main/groovy/com/zerocracy/stk/pmo/profile/invite_friend.groovy, src/test/resources/com/zerocracy/bundles/examiner_can_invite/_after.groovy
#1733 - removed invitation negative points
=> Removed invitation negative points

src/main/groovy/com/zerocracy/stk/pm/qa/add_reviews_to_qa_agenda.groovy, src/test/resources/com/zerocracy/bundles/adds_reviews_to_qa_agenda/_after.groovy, src/test/resources/com/zerocracy/bundles/adds_reviews_to_qa_agenda/_before.groovy, src/test/resources/com/zerocracy/bundles/adds_reviews_to_qa_agenda/claims.xml, src/test/resources/com/zerocracy/bundles/adds_reviews_to_qa_agenda/pmo_people.xml, src/test/resources/com/zerocracy/bundles/adds_reviews_to_qa_agenda/roles.xml
#1280 
* QA agenda is periodically extended by reviews where he/she is an inspector
=> #1280 periodically add reviews to QA agenda

src/main/groovy/com/zerocracy/stk/pm/bootstrap.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/make_payment.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/pay_extra.groovy, src/main/groovy/com/zerocracy/stk/pm/in/orders/resign_on_delay.groovy, src/main/groovy/com/zerocracy/stk/pm/publish_project.groovy, src/main/groovy/com/zerocracy/stk/pmo/awards/add_award_points.groovy, src/main/groovy/com/zerocracy/stk/pmo/awards/copy_negative_points_to_mentor.groovy, src/main/groovy/com/zerocracy/stk/pmo/awards/penalize_architect_for_boost.groovy, src/main/groovy/com/zerocracy/stk/pmo/awards/penalize_for_manual_assignment.groovy, src/main/groovy/com/zerocracy/stk/pmo/awards/penalize_for_refusal.groovy, src/main/groovy/com/zerocracy/stk/pmo/awards/penalize_for_same_user_github_assignment.groovy, src/main/java/com/zerocracy/tk/project/TkHiring.java, src/test/resources/com/zerocracy/bundles/bootstraps_a_project/claims.xml, src/test/resources/com/zerocracy/bundles/bootstraps_short_named_project/claims.xml, src/test/resources/com/zerocracy/bundles/publish_project/claims.xml
This is for #1162.
I wasn't exactly sure what is the proper way of continuing #1162, so I introduced a `@todo` but I'm open to improve it.
=> Separate adding award points from making payment

src/main/groovy/com/zerocracy/stk/pm/cost/funding/send_zold.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/pay_architect_for_release.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/vesting/transfer_shares.groovy, src/main/groovy/com/zerocracy/stk/pm/staff/notify_arc_report.groovy, src/main/java/com/zerocracy/entry/Pings.java
#1784
- added 2weeks pings
- added stakeholder to notify ARCs about PO reports
- minor fixes related to `Par` responses
=> Notify about PO reports

src/main/java/com/zerocracy/pm/staff/ProjectsRoles.java, src/main/java/com/zerocracy/tk/RqUser.java, src/main/java/com/zerocracy/tk/profile/RqLogin.java, src/test/java/com/zerocracy/pm/staff/ProjectsRolesTest.java
#1279: Moved common role checking code in `RqUser` and `RqLogin` to `ProjectsRoles`
=> #1279 ProjectsRoles to check user roles across all projects

src/main/resources/xsl/rfp.xsl
Let's add this short link to the video. Thanks.
=> RfP explanation video

src/main/scss/main.scss
Let's get rid of it and rely entirely on default look-and-feel from Tacit
=> removed Nunito font

src/main/scss/main.scss
@g4s8 and @yegor256 here is a solution to #1778, at least until we can perfect tables in tacit (or create a proper CSS lib to handle complex cases for tables.
Included in this change:
- rawgit cdn will become deprecated, replaced it (see https://rawgit.com/ )
- pointing to latest version of tacit (which includes table layout change, https://github.com/yegor256/tacit/releases/tag/1.4.1 )
Here's how `/board` page should look from now on:
**Desktop:**
**Mobile:**
**Note:** I'm not sure this is the right file to change to update `0crat.com`, point me out in the right direction if it's a different file.
=>  #1778 - improve table layout in board page

src/main/groovy/com/zerocracy/stk/pm/cost/pay_architect_for_pull_request.groovy, src/test/resources/com/zerocracy/bundles/upMobO_awards_points_to_arc_for_pull_request/_before.groovy
#1897 - pay ARC 10min only for merged pull requests
=> Pay arc for merged prs

src/test/resources/com/zerocracy/bundles/up2j5b_refresh_catalog/_after.groovy
=> Disabled catalog test

pom.xml, src/main/java/com/zerocracy/tk/profile/TkYoti.java
#1977 - updated yoti library to 2.0, fixed fasterxml.jackson dependency
=> Fixed yoti deps

src/main/groovy/com/zerocracy/stk/pm/refund.groovy, src/main/resources/com/zerocracy/radars/q-project.xml, src/test/resources/com/zerocracy/bundles/upTA7i_refund_project/_after.groovy, src/test/resources/com/zerocracy/bundles/upTA7i_refund_project/_before.groovy, src/test/resources/com/zerocracy/bundles/upTA7i_refund_project/claims.xml, src/test/resources/com/zerocracy/bundles/upTA7i_refund_project/estimates.xml, src/test/resources/com/zerocracy/bundles/upTA7i_refund_project/wbs.xml
#2007 - refund command for project
=> Implemented refund

src/main/java/com/zerocracy/pmo/Blanks.java, src/test/java/com/zerocracy/pmo/BlanksTest.java
#1974 - override blanks on update
=> Override blanks on update

src/main/groovy/com/zerocracy/stk/pm/change_project_option.groovy, src/main/groovy/com/zerocracy/stk/pm/in/orders/resign_on_delay.groovy, src/main/java/com/zerocracy/Xocument.java, src/main/java/com/zerocracy/farm/strict/StrictProject.java, src/main/java/com/zerocracy/pm/PktOptions.java, src/main/resources/com/zerocracy/radars/q-project.xml, src/test/java/com/zerocracy/pm/PktOptionsTest.java, src/test/resources/com/zerocracy/bundles/upnJ9i_modifies_days_to_close_task_option/_after.groovy, src/test/resources/com/zerocracy/bundles/upnJ9i_modifies_days_to_close_task_option/_before.groovy, src/test/resources/com/zerocracy/bundles/upnJ9i_modifies_days_to_close_task_option/claims.xml, src/test/resources/com/zerocracy/bundles/upnJ9i_modifies_days_to_close_task_option/roles.xml
#1937 - added project options stakeholder, using `daysToCloseTask` option for `resign_on_delay`
=> Project options

src/main/groovy/com/zerocracy/stk/internal/send_metrics.groovy, src/main/groovy/com/zerocracy/stk/pm/comm/notify_telegram.groovy
Little improvements. More coming.
=> #2032 better formatting

src/main/groovy/com/zerocracy/stk/internal/collect_revenue_metrics.groovy, src/main/java/com/zerocracy/pm/cost/PgLedger.java, src/test/java/com/zerocracy/pm/cost/PgLedgerITCase.java
=> Revenue metrics

src/main/groovy/com/zerocracy/stk/pm/staff/notify_arc_report.groovy
A small improvement to the text we send.
=> better text

src/main/groovy/com/zerocracy/stk/internal/send_metrics.groovy
Let's format them a bit better
=> better formatting

src/main/java/com/zerocracy/tk/TkJoin.java, src/main/resources/xsl/resume.xsl, src/test/java/com/zerocracy/tk/TkJoinTest.java
Original issue is https://github.com/zerocracy/farm/issues/1805
I am newcomer, my resume was sent second time couple days ago. @g4s8 has posted the answer when I have asked about status of my resume first time:
> Check http://0crat.com/join page, your resume should be here
So I have decided to dig a src and fix a problem.
=> #1805: TkJoinTest is not checking if join page is being rendered correctly

src/main/java/com/zerocracy/pmo/Resumes.java, src/main/java/com/zerocracy/tk/TkJoin.java, src/main/resources/xsl/resume.xsl, src/test/java/com/zerocracy/pmo/ResumesTest.java, src/test/java/com/zerocracy/tk/TkJoinTest.java
https://github.com/zerocracy/farm/issues/2056
=> #2056: Show Examiner if Resume has one

src/main/groovy/com/zerocracy/stk/pm/qa/start_qa_review.groovy
https://github.com/zerocracy/farm/issues/2061
=> #2061 When all QAs on vacation in the project, notify ARCs about that

src/main/java/com/zerocracy/tk/TkBoard.java
This should fix #1919 and hopefully fix the board layout :3
=> #1919: On the board, separate project languages with commas *and spaces*

src/main/groovy/com/zerocracy/stk/pm/cost/funding/contribute_by_stripe.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/fund_by_stripe.groovy, src/main/groovy/com/zerocracy/stk/pm/staff/roles/assign_rev_in_sandbox.groovy, src/main/groovy/com/zerocracy/stk/pm/staff/roles/kickout_from_sandbox.groovy, src/main/groovy/com/zerocracy/stk/pm/staff/roles/resign_rev_in_sandbox.groovy, src/main/groovy/com/zerocracy/stk/pmo/profile/apply_to_project.groovy, src/main/java/com/zerocracy/Xocument.java, src/main/java/com/zerocracy/farm/Assume.java, src/main/java/com/zerocracy/pmo/Catalog.java, src/main/java/com/zerocracy/tk/TkBoard.java, src/test/java/com/zerocracy/pmo/CatalogTest.java
#1453 - using sandbox flags in `catalog.xml` instead of hard-coded strings
=> Sandbox flags

src/main/groovy/com/zerocracy/stk/pm/in/impediments/register_impediment.groovy, src/test/resources/com/zerocracy/bundles/upWx5k_impediments/_after.groovy, src/test/resources/com/zerocracy/bundles/upWx5k_impediments/_before.groovy, src/test/resources/com/zerocracy/bundles/upWx5k_impediments/claims.xml, src/test/resources/com/zerocracy/bundles/upWx5k_impediments/orders.xml, src/test/resources/com/zerocracy/bundles/upWx5k_impediments/wbs.xml
#2081 - allow registering impediments only to job performers and users with `ARC` or `PO` role
=> Impediments fix

src/main/groovy/com/zerocracy/stk/internal/send_metrics.groovy, src/main/java/com/zerocracy/pm/cost/Ledger.java, src/main/java/com/zerocracy/pm/cost/PgLedger.java, src/test/java/com/zerocracy/pm/cost/PgLedgerITCase.java
#2092 - send active projects in daily report
=> Added projects to report

src/main/groovy/com/zerocracy/stk/pmo/profile/apply_to_project.groovy, src/main/java/com/zerocracy/Xocument.java, src/main/java/com/zerocracy/farm/strict/StrictProject.java, src/main/java/com/zerocracy/pm/staff/Applications.java, src/main/resources/xsl/project.xsl, src/test/java/com/zerocracy/pm/staff/ApplicationsTest.java, src/test/resources/com/zerocracy/bundles/upRPCH_apply_to_a_project/_after.groovy
#1349 - save applications to `applications.xml`
=> Applications

src/main/groovy/com/zerocracy/stk/pm/in/impediments/notify_user_on_impediment.groovy, src/main/groovy/com/zerocracy/stk/pm/in/impediments/register_impediment.groovy, src/main/groovy/com/zerocracy/stk/pm/in/impediments/remove_impediment.groovy, src/main/groovy/com/zerocracy/stk/pm/in/impediments/remove_waiting_label.groovy, src/main/java/com/zerocracy/farm/Assume.java, src/main/java/com/zerocracy/radars/github/Job.java
#2085 - impediment notifications fix
=> Fixed impediments notifications

src/main/groovy/com/zerocracy/stk/pmo/profile/change_option.groovy
PR for https://github.com/zerocracy/farm/issues/1906.
Added maxRevJobsInAgenda option to change_option.groovy.
=> #1906 - Add maxRevJobsInAgenda option to change_option.groovy

src/main/groovy/com/zerocracy/stk/pmo/awards/penalize_for_refusal.groovy, src/test/resources/com/zerocracy/bundles/up3m6w_elects_and_assigns_performer/bans.xml, src/test/resources/com/zerocracy/bundles/upR92D_elects_and_assigns_performer_when_debt/bans.xml
#1926 - penalize for refuse by new policy rules: https://www.zerocracy.com/policy.html#6
=> Refuse penalty depends on time

src/test/java/com/zerocracy/pm/time/MilestonesTest.java
PR for Issue #2051 unrecoverable failure Type: "Job milestoned".
Reproduced the problem with a unit test and added puzzle for further development.
=> Created testcase for adding milestones with space in name #2051  

src/test/resources/com/zerocracy/bundles/upMBdd_assign_role/_after.groovy
Fix for issue #1145 
jcabi-github was already updated to version 0.41 in a previous issue, which allowed this code to be uncommented.
=> Unignored fixed testcase in bundle upMBdd_assign_role #1145

src/main/groovy/com/zerocracy/stk/pm/in/orders/cancel_order.groovy, src/main/groovy/com/zerocracy/stk/pm/in/orders/request_order_start.groovy
#2227 - the error was caused by missing `age` parameter in `Order was canceled` claim. Added parameter to this claim on request order to start.
=> Added age parameter to cancel claims

pom.xml
=> Revert "Bump quartz from 2.2.1 to 2.3.2"

src/main/java/com/zerocracy/entry/ExtGithub.java, src/main/resources/com/zerocracy/_props.xml
Here we move to tokens, instead of login/password
=> #2306 tokens instead of login/password

src/main/groovy/com/zerocracy/stk/pm/staff/roles/kickout_from_sandbox.groovy
=> (#2050) Exempt myself from §33 (http://www.zerocracy.com/policy.html#33)
