src/test/resources/com/zerocracy/bundles/resigns_tasks_upon_quit/_after.groovy, src/test/resources/com/zerocracy/bundles/resigns_tasks_upon_quit/_before.groovy
#281 - `resigns_tasks_upon_quit` test fix; using `PMO` instead of `project`.
=> resigns_tasks_upon_quit test fix

src/main/resources/com/zerocracy/stk/pm/in/orders/cancel_order.groovy, src/test/resources/com/zerocracy/bundles/cancel_order/_after.groovy, src/test/resources/com/zerocracy/bundles/cancel_order/claims.xml
#499 - added `cancel_order` claim reason to Github comment message, the text for a reason is already defined, e.g. in `resign_on_delay`: "It is older than %d day(s), see §8".
=> Cancellation reason in Github comments

src/test/java/com/zerocracy/tk/project/TkFootprintTest.java
PR for #284 
The test in TkFootprintTest has been ``@Ignore``d in #155 (when the puzzle was created), but since then has been unignored, which means it's working.
I think ``FtParamTest`` was renamed to ``FtFarmTest``, which doesn't have any ``@Ignore``d tests either.
We are also not using Shippable anymore.
=> #284 Removed outdated puzzle

src/main/java/com/zerocracy/radars/slack/TkSlack.java, src/main/java/com/zerocracy/tk/TkDump.java
PR for #425 
SInce the dump cannot be downloaded yet (waiting for #400, apparently) and since it's not ok to just wait indefinetely, I did another improvement: 
TkSlack would create an ``AsyncFunc`` to refresh Slack asynchronously, but the reference was not assigned, thus that ``AsyncFunc`` would become an "island object", trouble for the gc. Add to that the fact that it starts one of more different threads inside, it was probably a memory leak point. So, AsyncFunc is now an attribute of TkSlack.
=> #425 Fixed possible memory leak

src/main/resources/com/zerocracy/stk/pm/in/orders/finish_stale_github_order.groovy, src/main/resources/com/zerocracy/stk/pm/scope/wbs/remove_stale_github_ticket_from_wbs.groovy
#368 - use `closed_at` instead of timestamp of `CLOSE` event
=> Fix for stale jobs

src/main/java/com/zerocracy/radars/github/ReIfAddressed.java, src/test/java/com/zerocracy/radars/github/ReIfAddressedTest.java
PR for https://github.com/zerocracy/datum/issues/260
``ReIfAddressed``'s purpose is to check if the Github comment starts with 0crat's handle (``@0crat``). However, instead of simply checking ``comment.trim().startsWith(self)``, it checks for ``contains`` and tries to match some regex with single line/multiline...? That regex has no purpose since it doesn't apply any change to the comment, one that maybe would benefit the next ``Response``. 
I removed the ``contains`` + regex matching and simply used ``startsWith``. The exception message already says "You must always start your message with my name" -- also ``ReQuestion`` (the encapsulated Response, to which the Comment is passed on) tries to parse the body as if it starts with the handle.
=> Removed useless regex check

src/main/resources/com/zerocracy/stk/pm/staff/roles/assign_role.groovy
Pr for #229 
The code is rather ugly and it cannot easily be tested because MkUser does not behave the same as RtUser -- MkUser.json() simply returns ``{login: username}`` for any login input. In order to properly test this scenario, we would need another mock implementation of User, decorate the test Github instance somehow (its Users, to be more precise, they should return another version of MkUser). 
Furthermore, the user ``Github`` instance is wraped inside ``ExtGithub`` scalar and cannot be changed at all -- that class should be refactored.
=> #229 assign_role fails if user is not on Github

src/main/java/com/zerocracy/tk/project/TkClaim.java, src/test/java/com/zerocracy/tk/project/TkClaimTest.java
Pr for #489 
Inside TkClaim its children are also read from the Footprint (the Claims which have the ``cause`` element equal to this claim's id).
Left a puzzle for editing ``claim.xsl`` in such a way that its children are also displayed.
=> #489 read children in TkClaim + puzzle

src/main/java/com/zerocracy/radars/slack/ReInvite.java
Possible fix for [this issue](https://github.com/zerocracy/datum/issues/163)
I feel like there is no so much sense on disconnecting and then connecting again, since connect should already happen (as otherwise we don't receive this event). I think that it might be the possible cause for the issue, as on the new connection this event wasn't yet addressed and thus we get it again and again until the refresh is happen. Let's see if this will fix the issue. If not I will continue investigation.
Then the most probable reason might be the fact that simple-slack-api library has some bug and it is keeping sending the event.
=> 0crat iz verbose, when invited to channel

README.md, src/test/java/com/zerocracy/BundlesTest.java
PR for #415 
Tested in IntelliJ: ``Run->Edit Configurations->VM Options``: ``-DskipBundlesTest``
Tested in terminal: 
- ``mvn clean install`` -> 1m 30s
- ``mvn clean install -DskipBundlesTest`` -> 40s
=> #415 skipBundlesTest option

src/main/java/com/zerocracy/pmo/Agenda.java, src/main/resources/com/zerocracy/stk/pm/destroy.groovy, src/test/java/com/zerocracy/pmo/AgendaTest.java
PR for #497
Added and tested method ``Agenda.removeAll(...)``. The alternative was to call ``Agenda.item()`` and run the xpath query inside ``destroy.groovy``, but I think it's better to keep XML classes out of the groovy scripts, let them be encapsulated.
=> #497 Agenda.removeAll() on destroy

src/main/resources/com/zerocracy/stk/pmo/agenda/delete_stale_jobs.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_jobs/_after.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_jobs/_setup.xml
#728: At "Ping hourly" event, take 5 random people. Go through each job in Agenda to check whether they correspond to existing orders in all of their projects. If there is no order remove the job from the Agenda.
=> #728 Delete stale jobs from Agenda

src/main/java/com/zerocracy/tools/Signature.java
#853: A brief explanation is in order.
The issue is very subtle. The stack trace of the original error shows us the following:
```
Caused by: java.io.IOException: Stream closed
at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
at java.io.OutputStream.write(OutputStream.java:116)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
at org.cactoos.io.TeeInputStream.close(TeeInputStream.java:99)
at org.cactoos.io.LengthOf.lambda$new$0(LengthOf.java:81)
at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
at …
```
=> #853 Explicit input redirect for Signature processes

src/main/java/com/zerocracy/tools/Signature.java
#900: This is another attempt to fix `SignatureTest` which was started in #853.
The current fix attempts to address an apparent race condition, where the input of the "sign" process (via `sign.getOutputStream()` becomes unavailable before we are able to send data to it. To address this the data is first read into a file, which is then redirected as input into the "sign" process.
=> #900 Redirect sign process input from file

src/main/xsl/artifact.xsl, src/test/java/com/zerocracy/tk/project/TkArtifactTest.java
#438 
* removed notice about Chrome from artifacts
* added test to check that
There is no need for that information (as no other pages have it) and when #1024 is merged it won't be true
=> #438 removed chrome notice

src/main/java/com/zerocracy/farm/S3Item.java
#987 - read temp file to memory before uploading to S3.
`Files.newInputStream()` opens new stream in `S3Item` which was never closed,
AWS-sdk is working asynchronously, so actual stream reading operation was invoked in different thread than file stream was created, `Files.newInputStream` implemented is not very clear, but looks like it may close opened previously channel-stream.
This PR ensures that temporary file is fully read before uploading (sending data to another thread). Also now we close file stream for temporary file right after read it to memory.
=> S3 upload fix

src/main/java/com/zerocracy/radars/github/Rebound.java, src/main/java/com/zerocracy/radars/github/TkGithub.java, src/test/java/com/zerocracy/radars/github/TkGithubTest.java
#831 - reproduced and fixed exception: it happens when form body is not urlencoded and contains `%` characters.
=> Handling not urlencoded payload

src/main/groovy/com/zerocracy/stk/package-info.java, src/main/java/com/zerocracy/pmo/Agenda.java, src/test/java/com/zerocracy/pmo/AgendaTest.java
PR for #843.
I've added an ability to set job's title for agenda. As well I've added tests for this new method.
Finally, I've added a new puzzle about creating a new stakeholder `set_agenda_title_from_github.groovy` as I wasn't able to do that in 30 minutes (was fighting with code style for changed classes).
=> #843: add an ability to set job's title for agenda.

pom.xml
#601: The problem is that reserving the ports is subject to a race condition; any process might be able to grab the port between execution of `reserve-network-port` and starting of Dynamo DB test.
This isn't so much a fix as it is a mitigation:
* Moved `reserve-network-port` goal to `pre-integration-test` phase. [By default](https://www.mojohaus.org/build-helper-maven-plugin/reserve-network-port-mojo.html) it runs under `process-test-classes` phase, which means it runs before we even execute unit tests. This is a hazard because the unit tests themselves allocate some network connections. Now the port reservation is done right before the Dynamo DB test itself to narrow down the time window between reservation and execution.
* Use the recommended [dynamic ports …
=> #601 Fix "Address already in use" issue with DynamoDB in Maven build

src/main/java/com/zerocracy/tk/TkTeam.java
#1121 - hide speed and agenda on `/team` page
=> Temporary disabled speed and agenda

src/main/java/com/zerocracy/radars/slack/RealSkSession.java, src/main/java/com/zerocracy/radars/slack/SkSession.java, src/test/java/com/zerocracy/radars/slack/RealSkSessionTest.java, src/test/resources/com/zerocracy/bundles/notify_in_slack_without_user/_before.groovy
PR for #89. 
I've added a new interface SkSession that should be used instead of SlackSession which is closed for decorating. As well I've added an implementation of this interface - RealSkSession that wraps an instance of SlackSession.
I've added two new puzzles:
- integrate SkSession so that it replaces SlackSession in the code, 
- create fake SkSession class that can be used in tests.
=> #89: Implement SkSession class to wrap a real Slack session 

src/main/groovy/com/zerocracy/stk/pm/staff/roles/assign_role.groovy, src/test/resources/com/zerocracy/bundles/assign_role/_after.groovy, src/test/resources/com/zerocracy/bundles/assign_role/_before.groovy, src/test/resources/com/zerocracy/bundles/assign_role/claims.xml, src/test/resources/com/zerocracy/bundles/assign_role/people.xml
#989 - check access in repo on assign role, if repository is private and user is not a collaborator `assign_role` will fail.
Test is not working because of bug: https://github.com/jcabi/jcabi-github/issues/1421
=> Check repo access on assign role

src/main/java/com/zerocracy/tk/TkJoin.java, src/test/java/com/zerocracy/tk/TkJoinTest.java
For #1147:
- Created test in `TkJoinTest` which tests if user is seeing page telling that he /she already has a mentor;
- Created test in `TkJoinTest` which tests if user is seeing resume on page, it he / she already has a resume.
- Added in puzzle the info about ticket implementation.
=> For #1147: Each user should see the status of his/her resume at /join.

src/test/java/com/zerocracy/farm/S3ItemTest.java
#556: It appears that the original bug was fixed in PR #1065 (see issue #987). In that PR, the original `Files.newInputStream` implementation was changed into the existing one, avoiding the `ClosedChannelException` issue. I managed to reproduce the bug by reverting to the prior code.
Re-enabled test (and removed a couple of extraneous warning suppressions as well).
=> #556 Re-enable S3ItemTest.handleThreadInterruptionCorrectly

pom.xml, src/main/groovy/com/zerocracy/stk/pmo/people/remove_stale_users.groovy, src/test/resources/com/zerocracy/bundles/remove_stale_users/_after.groovy
#896 
* updated jcabi-github version
* uncomennted remove stale users test
* added a mock behavior for `exists` (non-mock version is not possible with current jcabi-github implementation)
=> #896 fixed test

.travis/run.sh
When using `--quiet` no INFO messages from qulice are shown, I removed it.
=> Fix travis build so we will see qulice errors

src/main/groovy/com/zerocracy/stk/pmo/profile/penalize_for_breakup.groovy, src/test/resources/com/zerocracy/bundles/dont_penalize_pmo_member_for_breakup/_after.groovy, src/test/resources/com/zerocracy/bundles/dont_penalize_pmo_member_for_breakup/_before.groovy, src/test/resources/com/zerocracy/bundles/dont_penalize_pmo_member_for_breakup/_setup.xml, src/test/resources/com/zerocracy/bundles/dont_penalize_pmo_member_for_breakup/claims.xml, src/test/resources/com/zerocracy/bundles/dont_penalize_pmo_member_for_breakup/people.xml
#1243: Modified `penalize_for_breakup.groovy` stakeholder to avoid penalizing PMO members when breaking up with students. Added Bundles test case for this scenario.
=> #1243 Don't penalize PMO project members for breakup

src/main/java/com/zerocracy/farm/StkSafe.java, src/main/java/com/zerocracy/pm/Claims.java, src/test/java/com/zerocracy/farm/StkSafeTest.java, src/test/java/com/zerocracy/pm/ClaimsTest.java
#1245 
- added a check in StkSafe that won't send out `Error` claim if the exception is thrown from `Claims.add` method
- removed todo
=> #1245 Fix handling of errors during adding of claims

src/main/java/com/zerocracy/pmo/banks/Crypto.java
Result from #980:
We need to drop Etherium support from Zerocracy
Remove ETH support mentioned in Policy (https://www.zerocracy.com/policy.html#20)
Remove ETH wallets support informing that ETH cannot be used when user tries to use it.
=> For #980: 0crat doesn't succeed paying via ethereum

src/main/groovy/com/zerocracy/stk/pmo/agenda/update_person_agenda_count.groovy, src/main/java/com/zerocracy/pmo/People.java, src/test/resources/com/zerocracy/bundles/refresh_person_job_count_on_agenda_update/_after.groovy, src/test/resources/com/zerocracy/bundles/refresh_person_job_count_on_agenda_update/_before.groovy, src/test/resources/com/zerocracy/bundles/refresh_person_job_count_on_agenda_update/claims.xml, src/test/resources/com/zerocracy/bundles/refresh_person_job_count_on_agenda_update/people.xml
#841: Agenda count is now stored in `people.xml` and refreshed for each `Agenda was updated` claim. Added corresponding `BundlesTest` case to suit.
=> #841 Store agenda count in people.xml

src/test/java/com/zerocracy/radars/slack/SlackRadarTest.java
#1262 
SlackRadar test was using ExtSlack singleton to retrieve the sessions, and those were cached based on default FkFarm constructor (which just uses canonical class name) - as a result one test was closing the sessions of another one.
Fixed by adding unique identifier for each FkFarm in SlackRadar tests.
=> #1262 fix SlackRadar tests

pom.xml, src/main/groovy/com/zerocracy/stk/pm/cost/make_payment.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/vesting/transfer_shares.groovy, src/test/resources/com/zerocracy/bundles/transfers_correct_shares/_after.groovy, src/test/resources/com/zerocracy/bundles/transfers_correct_shares/_before.groovy, src/test/resources/com/zerocracy/bundles/transfers_correct_shares/claims.xml, src/test/resources/com/zerocracy/bundles/transfers_correct_shares/equity.xml, src/test/resources/com/zerocracy/bundles/transfers_correct_shares/people.xml, src/test/resources/com/zerocracy/bundles/transfers_correct_shares/roles.xml
#1281: See https://github.com/zerocracy/farm/issues/1281#issuecomment-401293773 for explanation of the bug.
The fix involves using the number of minutes, which is always present as a param to `Make payment`. In case `cash` param is absent, the actual cash paid is computed based on the project rate. I patterned this after a similar logic in `make_payment.groovy`: https://github.com/zerocracy/farm/blob/e485549aa173362d9e8f12ccbc9264e929678fa7/src/main/groovy/com/zerocracy/stk/pm/cost/make_payment.groovy#L51-L56
There is a proposed larger fix for inconsistencies in `Make payment` (see #1162). In the meantime this should allow the correct equity to be awarded on future completed tasks.
=> #1281: Workaround for incorrect equity computation

src/main/groovy/com/zerocracy/stk/pmo/agenda/set_agenda_title_from_github.groovy, src/test/resources/com/zerocracy/bundles/set_agenda_title_from_github/claims.xml
'set title' stakeholder was attached to `Start order` which happens before the agenda is updated, so it couldn't update the tile in agenda.
Updated it to attach to `Agenda was updated`.
=> correcting claim type for set title stk

src/main/groovy/com/zerocracy/stk/pmo/speed/update_person_speed.groovy, src/main/java/com/zerocracy/pmo/People.java, src/test/resources/com/zerocracy/bundles/refresh_person_average_speed_on_speed_update/_after.groovy, src/test/resources/com/zerocracy/bundles/refresh_person_average_speed_on_speed_update/_before.groovy, src/test/resources/com/zerocracy/bundles/refresh_person_average_speed_on_speed_update/claims.xml, src/test/resources/com/zerocracy/bundles/refresh_person_average_speed_on_speed_update/people.xml
#1267: Added `update_person_speed.groovy` stakeholder. It watches for `Speed was updated` claim, computes the latest average speed, and stores it in `people.xml`. Added `BundlesTest` case for it.
=> #1267 Added Stakeholder to compute average speed per person

src/main/java/com/zerocracy/farm/StkSafe.java, src/main/java/com/zerocracy/pm/ClaimIn.java, src/main/java/com/zerocracy/pm/Claims.java, src/test/java/com/zerocracy/farm/StkSafeTest.java, src/test/java/com/zerocracy/pm/ClaimInTest.java
#1317 - do not submit `Error` claims in `StkSafe` if reason was another `Error` claim
=> Don't resubmit error claims

src/main/java/com/zerocracy/radars/github/RbRelease.java, src/main/java/com/zerocracy/radars/github/TkGithub.java, src/test/java/com/zerocracy/radars/github/RbReleaseTest.java
#1269: Added `RbRelease` to receive Github [release event](https://developer.github.com/v3/activity/events/types/#releaseevent). This `Rebound` implementation responds to `published` Github action, and generates a claim `Release was published`.
Added puzzle for further implementation of stakeholder that responds to the claim in order to pay the [architect release bonus](http://www.zerocracy.com/policy.html#53).
=> #1269 RbRelease for receiving Github release event

pom.xml
#1041 - excluded `RsPageTest`, `TkAwardsTest`, `TkAgendaTest`, `TkVacanciesTest` from failing build log: https://gist.github.com/proshin-roman/6375ad56eeac773d3253ee8764038ede
=> Build on windows

src/main/java/com/zerocracy/pm/in/Impediments.java, src/main/resources/com/zerocracy/radars/q-tracker.xml, src/test/java/com/zerocracy/pm/in/ImpedimentsTest.java
PR for #1016 
* Registered the ``continue`` command inside ``q-tracker.xml``
* Added method ``Impediments.remove(...)``
* Added unit test for ``Impediments.remove(...)``
* Left puzzle for continuing implementation of the stakeholder.
=> #1016 Impediments.remove(...) + unit test and puzzle

src/test/java/com/zerocracy/XocumentTest.java
#1037: Added `XocumentTest.concurrentlyModifiesXml`, to check whether multiple concurrent threads can modify the same document. The test currently fails, and a puzzle was added to fix the error.
=> #1037 Add Xocument test for concurrent modification.

src/main/groovy/com/zerocracy/stk/pmo/profile/invite_friend.groovy
#1166: In some cases, invite command throws an exception. The problem is that in `invite_friend.groovy`, we are trying to get the user's `name` field (display name) from their JSON. This is not always present, and Github sometimes returns `null` for it. For example:
```json
{
"login": "KDobarskyi",
"id": 29274427,
"node_id": "MDQ6VXNlcjI5Mjc0NDI3",
"avatar_url": "https://avatars0.githubusercontent.com/u/29274427?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/KDobarskyi",
"html_url": "https://github.com/KDobarskyi",
"followers_url": "https://api.github.com/users/KDobarskyi/followers",
"following_url": "https://api.github.com/users/KDobarskyi/following{/other_user}",
"gists_url": "https://api.github.com/users/KDobarskyi/gists{/gist_id}",
"starred_url": …
```
=> #1166 Handle JSON null user name values in invite_friend.groovy

appveyor.yml, pom.xml, src/test/resources/com/zerocracy/bundles/changes_user_rate/_after.groovy, src/test/resources/com/zerocracy/bundles/changes_user_rate/_before.groovy, src/test/resources/com/zerocracy/bundles/changes_user_rate/claims.xml, src/test/resources/com/zerocracy/bundles/changes_user_rate/people.xml, src/test/resources/com/zerocracy/bundles/changes_user_rate/roles.xml
#1088 
* removed exclusion for groovy scripts
* decreased coverages so the build passes (this will stop the coverage to drop)
* added todo to add more tests for stakeholders and increase the coverage
* added a missing test for changing of user rate
=> #1088 included groovy scripts in jacoco coverage

src/main/java/com/zerocracy/cash/Cash.java, src/main/java/com/zerocracy/pm/cost/Estimates.java, src/test/java/com/zerocracy/pm/cost/EstimatesTest.java
#1265 
* added a check in `Estimates` if the `Cash` object is unified (contains single currency) and if not then do an exchange to USD
* added `unified` method to `Cash`
=> #1265 fix multi-currency estimates

src/main/java/com/zerocracy/tk/TkTeam.java, src/test/java/com/zerocracy/tk/TkTeamTest.java
#1123 After the fixes in #841 and #1267, speed and agenda data for users are now stored in `people.xml` ("jobs" element for agenda) instead of being computed on each page load. This fix will display those elements on the Teams page.
=> #1123 Re-enable Jobs and Agenda display in Team page

pom.xml, src/main/java/com/zerocracy/Xocument.java, src/main/java/com/zerocracy/farm/ruled/RdAuto.java, src/main/java/com/zerocracy/farm/ruled/RdIndex.java, src/main/java/com/zerocracy/farm/ruled/RdRules.java, src/main/java/com/zerocracy/tk/XeXsl.java
#360 - using soft references for caching `xml`, `xsd` and `xsl` documents instead of keeping them in memory forever.
=> Soft references for caching

src/main/java/com/zerocracy/SafeSentry.java, src/main/java/com/zerocracy/entry/Main.java, src/main/java/com/zerocracy/farm/StkSafe.java, src/main/java/com/zerocracy/farm/sync/Terminator.java, src/main/java/com/zerocracy/radars/github/RbSafe.java, src/main/java/com/zerocracy/radars/github/ReSafe.java, src/main/java/com/zerocracy/radars/slack/ReSafe.java, src/main/java/com/zerocracy/radars/telegram/ReSafe.java, src/main/java/com/zerocracy/tk/TkApp.java, src/main/resources/log4j.properties, src/test/java/com/zerocracy/SafeSentryTest.java
#1426: Added `SafeSentry` class, which wraps errors thrown by Sentry API. Added unit test to check that exceptions thrown by Sentry are logged.
=> #1426 Added SafeSentry

src/main/groovy/com/zerocracy/stk/pmo/agenda/delete_stale_jobs.groovy, src/main/java/com/zerocracy/pm/qa/Reviews.java, src/test/java/com/zerocracy/pm/qa/ReviewsTest.java
#1414: `delete_stale_jobs.groovy` does not work properly for QA inspection tasks. The reason is that `delete_stale_jobs` looks at `Orders`, but QA inspection jobs are actually in `Reviews`.
In order to avoid this bug:
1. Disabled it in case the person has `QA` role in the project. 
2. `Reviews.findByInspector()` added to find all QA jobs by inspector.
3. Added puzzle for proper implementation.
=> #1414 Disable delete_stale_jobs for QA inspectors

src/main/resources/xsl/profile.xsl, src/test/java/com/zerocracy/tk/profile/TkProfileTest.java
#1193 
* using table to display current debts values
* added todo to refactor after changes in datum (https://github.com/zerocracy/datum/issues/375) are complete
Table will look like this:
=> #1193 using table to display debts

src/main/java/com/zerocracy/farm/StkSafe.java
For #733: I've discovered that the problem of exception swallowing in `BundlesTest` happens due to `StkSafe` treating exceptions generated in code as a `Notify` claim directed to the `test` channel, and then these exceptions are treated like any other notifications and don't break the test execution. I've added a `@todo` to the code explaining and narrowing the problem of #733 o `StkSafe`.
=> For #733: Added todo for fixing the problem.

src/main/java/com/zerocracy/radars/github/RbMilestone.java, src/test/java/com/zerocracy/radars/github/RbMilestoneTest.java
#1169: Fix for `RbMilestone`. Prior to this fix, `RbMilestone.react` was creating a claim but wasn't actually posting it to any project, which means the claim isn't actually being received anywhere. This has been rectified.
=> #1169 Fix for RbMilestone

src/test/java/com/zerocracy/BundlesTest.java, src/test/resources/com/zerocracy/bundles/fetches_subdirectories/_after.groovy, src/test/resources/com/zerocracy/bundles/fetches_subdirectories/_before.groovy, src/test/resources/com/zerocracy/bundles/fetches_subdirectories/_setup.xml, src/test/resources/com/zerocracy/bundles/fetches_subdirectories/claims.xml, src/test/resources/com/zerocracy/bundles/fetches_subdirectories/options/foo.xml
#1438: Fixed bug where `BundlesTest` could not fetch resources from the bundle subdirectories.
The problem was that it tried to get the XML path relative to the bundle path. However, by checking `lastIndexOf('/')`, it ended up eating the subdirectory path as well:
* `com/zerocracy/bundles/fetches_subdirectories/options/foo.xml` -> `foo.xml`
This was fixed so that the relative path is now checked against not just `/` but the entire bundle path (e.g. `com/zerocracy/bundles/fetches_subdirectories/`
* `com/zerocracy/bundles/fetches_subdirectories/options/foo.xml` -> `options/foo.xml`
Also added a bundles test to see if it can get project file contents both from the bundle home directory and subdirectory.
=> #1438 BundlesTest can now fetch resources from subdirectories

src/main/groovy/com/zerocracy/stk/pm/in/orders/resign_on_delay.groovy, src/test/java/com/zerocracy/BundlesTest.java, src/test/resources/com/zerocracy/bundles/dont_resign_on_delay_unfunded_project/_after.groovy, src/test/resources/com/zerocracy/bundles/dont_resign_on_delay_unfunded_project/_before.groovy, src/test/resources/com/zerocracy/bundles/dont_resign_on_delay_unfunded_project/claims.xml, src/test/resources/com/zerocracy/bundles/dont_resign_on_delay_unfunded_project/orders.xml, src/test/resources/com/zerocracy/bundles/dont_resign_on_delay_unfunded_project/roles.xml, src/test/resources/com/zerocracy/bundles/dont_resign_on_delay_unfunded_project/wbs.xml, src/test/resources/com/zerocracy/bundles/resign_on_delay/_before.groovy
#1116 
- added test for validating that neither DEV nor REV jobs are resigned for unfunded projects
- fixed problem in resign_on_delay.groovy
=> #1116 fix resign on delay for unfunded projects

src/main/java/com/zerocracy/entry/Ping.java, src/test/java/com/zerocracy/entry/PingTest.java
#1502 - catch `IllegalStateException` in `Ping` and retrow as `JobExecutionException` to indicate that job was failed.
=> Ping errors

src/main/java/com/zerocracy/tk/TkJoin.java, src/test/java/com/zerocracy/tk/TkJoinTest.java
#1179: `TkJoinTest.showsThatUserAlreadyHasMentor()` revised and enabled.
Note to REV/ARC: This seems like a small change for me to do only "half" the puzzle, but the design of `TkJoin` seems to have changed rather significantly from the assumptions of the puzzle. I spent quite a bit of time with the test revisions, so I left the display of the resume for a later puzzle.
=> #1179 Enable TkJoinTest.showsThatUserAlreadyHasMentor()

pom.xml, src/main/java/com/zerocracy/entry/ClaimsOf.java, src/main/java/com/zerocracy/entry/ExtSqs.java, src/main/java/com/zerocracy/entry/PropsAwsCredentials.java, src/main/java/com/zerocracy/entry/ValidClaims.java, src/main/java/com/zerocracy/pm/ClaimOut.java, src/main/java/com/zerocracy/pm/ClaimsSqs.java, src/main/resources/com/zerocracy/_props.xml, src/test/java/com/zerocracy/entry/ClaimsOfITCase.java, src/test/java/com/zerocracy/entry/PingTest.java, src/test/java/com/zerocracy/farm/StkSafeTest.java, src/test/java/com/zerocracy/farm/reactive/AsyncFlushTest.java, src/test/java/com/zerocracy/farm/reactive/BrigadeTest.java, src/test/java/com/zerocracy/farm/reactive/DefaultFlushTest.java, src/test/java/com/zerocracy/farm/reactive/RvProjectTest.java, src/test/java/com/zerocracy/farm/ruled/RdFarmTest.java, src/test/java/com/zerocracy/pm/ClaimOutTest.java, src/test/java/com/zerocracy/pm/ClaimsSqsITCase.java, src/test/java/com/zerocracy/radars/ClaimOnQuestionTest.java, src/test/java/com/zerocracy/radars/github/RbAddToMilestoneTest.java, src/test/java/com/zerocracy/radars/github/RbMilestoneTest.java, src/test/java/com/zerocracy/radars/github/RbOnBugTest.java, src/test/java/com/zerocracy/radars/github/RbOnCloseTest.java, src/test/java/com/zerocracy/radars/github/ReQuestionTest.java, src/test/java/com/zerocracy/radars/slack/ReProfileTest.java, src/test/java/com/zerocracy/tk/project/reports/AwardChampionsTest.java, src/test/java/com/zerocracy/tk/project/reports/OrderChampionsTest.java, src/test/java/com/zerocracy/tk/project/reports/OrdersGivenByWeekTest.java, src/test/resources/com/zerocracy/_props.xml
#1480 using SQS FIFO queues instead of `claims.xml` file.
- Added `ClaimsSqs` implementation
- Using `ClaimsSqs` in `ClaimsOf` if credentials are provided
- Creating a queue for project if it doesn't exist
- Added integration tests for SQS queues
- Added `ValidClaims` to validate claims before submitting to SQS
=> SQS claims

src/main/java/com/zerocracy/farm/sync/Terminator.java, src/test/java/com/zerocracy/farm/sync/TerminatorTest.java
#721 
There were 2 main problems in Terminator.killer:
1. it called unlock even when lock was not acquired
2. it tries to use  `this.submit(project, file, lock);` to re-submit itself, but it did not work because `this.killers` still contains `project`. And if wasn't for that, it would reference the wrong thread (the terminator thread), instead of the thread that originally called `Terminator.submit`.
=> #721 Fixing Terminator.killer that did not correctly re-submitted itself

src/main/groovy/com/zerocracy/stk/pm/in/orders/assign_performer.groovy, src/main/groovy/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy, src/main/java/com/zerocracy/pm/qa/Reviews.java, src/main/java/com/zerocracy/pm/staff/Elections.java, src/test/java/com/zerocracy/pm/qa/ReviewsTest.java
#1553: Slightly speed up assign_performer.groovy and elect_performer.groovy by loading all Orders and Reviews in-memory to avoid repeated XPath lookups.
Meanwhile, the biggest bottleneck is in `Elections`, because we do a XSL transform in order to get the results of an election. I propose a major change to this in the puzzle that I added.
=> #1553 Avoid repeated XPath lookups of Orders and Reviews

src/main/java/com/zerocracy/claims/ClaimsRoutine.java, src/main/java/com/zerocracy/claims/proc/AsyncProc.java, src/main/java/com/zerocracy/entry/Main.java, src/main/java/com/zerocracy/farm/sync/SyncFarm.java, src/main/java/com/zerocracy/shutdown/ShutdownFarm.java, src/main/java/com/zerocracy/shutdown/package-info.java, src/test/java/com/zerocracy/claims/ClaimsRoutineITCase.java, src/test/java/com/zerocracy/farm/sync/SyncFarmTest.java, src/test/java/com/zerocracy/shutdown/ShutdownFarmTest.java, src/test/java/com/zerocracy/shutdown/package-info.java
#963 - stop accepting new claims when shutdown called and wait for all submited claims to be processed, then close the farm.
=> Implemented shutdown

src/main/java/com/zerocracy/pmo/Resumes.java, src/main/java/com/zerocracy/tk/TkApp.java, src/main/java/com/zerocracy/tk/TkJoin.java, src/main/java/com/zerocracy/tk/TkJoinPost.java, src/main/resources/xsl/resume.xsl, src/test/java/com/zerocracy/tk/TkJoinPostTest.java, src/test/java/com/zerocracy/tk/TkJoinTest.java
For #1506: This ticket is too big to be resolved in only 30 minutes, so I've had to break it:
- Added puzzle for creating `Resumes.resume(login)`
- Extracted `/join-post` logic into `TkJoinPost` and left `/join` logic into `TkJoin`
- Fixed `TkApp` according new `TkJoin` and `TkJoinPost` classes
- Added `resume.xsl`
- Added todo for continuing implementation.
=> For #1506: Show resume in /join if user already has resume.

src/test/resources/com/zerocracy/bundles/ping_after_pr_completed/_after.groovy, src/test/resources/com/zerocracy/bundles/ping_after_pr_completed/_before.groovy, src/test/resources/com/zerocracy/bundles/ping_after_pr_completed/claims.xml, src/test/resources/com/zerocracy/bundles/ping_after_pr_completed/roles.xml
#487 
Checking the footprint provided [here](https://github.com/zerocracy/farm/issues/487#issuecomment-401525930), the problem would be a `Start order` issued after the pr finished and points awarded. Searching current stalkholders, the one that would issue such claim with the attributes in the footprint would be `assign_performer.groovy`. As this stakeholder consumes `Ping` claims, I am creating a test that has a ping claim after the pr completed.
=> #487 Test ping after pr completed does not reassign

pom.xml, src/test/java/com/zerocracy/pm/FootprintTest.java
#1167 
An internal thread-safety bug in Xembly can cause errors when it is used is multiple threads. It was the cause of the [error found during FootprintTest](https://github.com/zerocracy/farm/issues/1167#issuecomment-410485364). This bug was fixed in https://github.com/yegor256/xembly/issues/82 and released in Xembly 0.22.1. This PR updates Xembly to fix this problem.
=> #1167: Update Xembly to 0.22.1

src/main/java/com/zerocracy/claims/ClaimsRoutine.java, src/main/java/com/zerocracy/claims/proc/CountingProc.java, src/main/java/com/zerocracy/entry/Main.java, src/test/java/com/zerocracy/claims/ClaimsRoutineITCase.java, src/test/java/com/zerocracy/claims/proc/CountingProcTest.java
#1539 
* New claims now won't be read from SQS if all the threads processing claims are still working
=> #1539 block processing of new claims if old ones are still in flight

src/main/java/com/zerocracy/claims/ClaimsRoutine.java, src/main/java/com/zerocracy/claims/proc/AsyncProc.java, src/main/java/com/zerocracy/entry/Main.java
#1567: The issue with the duplicate claims is that we are neglecting the message [visibility timeout](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html). When a message is received, that message will be reserved and not be visible, but it won't be removed until we actually delete it. However, if it is not deleted within the grace period specified by the visibility timeout, it will be visible and may be retrieved again. The default message visibility is 30 seconds, I am not sure what the setting of our queue is but 30 seconds is probably too short to go through the received claims.
I've set the timeout to two minutes. Then, I also added a routine to reset the message visibility timeout for any messages that have not been processed yet. …
=> #1567 Extend message visibility timeout of SQS claims messages

src/main/groovy/com/zerocracy/stk/pmo/agenda/delete_stale_jobs.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_qa_jobs/_after.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_qa_jobs/_before.groovy, src/test/resources/com/zerocracy/bundles/delete_stale_qa_jobs/_setup.xml, src/test/resources/com/zerocracy/bundles/delete_stale_qa_jobs/claims.xml, src/test/resources/com/zerocracy/bundles/delete_stale_qa_jobs/people.xml
For #1448:
- Corrected `delete_stale_jobs.groovy` for cleaning stale QA jobs
- Added bundle test for this condition
=> #1448: Cleanup of stale QA jobs.

src/main/java/com/zerocracy/Measured.java, src/test/java/com/zerocracy/MeasuredTest.java
For #1172:
- Added `Measured` decorator skeleton for measuring `Stakeholder` execution time;
- Added test for assuring that `Measured` is measuring;
- Left puzzles for continue impelentation.
=> #1172: Add performance metrics.

src/main/resources/xsl/board.xsl, src/test/java/com/zerocracy/tk/TkBoardTest.java
#1082 
All funded projects that have deficit will have a "no funds" displayed instead of negative cash amount.
=> #1082 properly show underfunded projects

src/main/java/com/zerocracy/claims/ClaimsRoutine.java, src/main/java/com/zerocracy/claims/proc/ExpiryProc.java, src/main/java/com/zerocracy/entry/Main.java, src/test/java/com/zerocracy/claims/proc/ExpiryProcTest.java
#1534: Added `ExpiryProc`, which checks for `expires` attribute in SQS claims messages. If expired, the message is skipped.
=> #1534 ExpiryProc

src/test/java/com/zerocracy/tk/TkAppTest.java
For #512:
- Added test for `GET http://www.0crat.com/?PsByFlag=PsGithub&code=1257b773ba07221e7eb5`
- Added test for `GET http://www.0crat.com/?PsByFlag=PsGithub`
- Left todo for fixes.
=> #512: Test for exception on http://www.0crat.com/?PsByFlag=PsGithub

src/main/java/com/zerocracy/claims/BatchClaims.java, src/test/java/com/zerocracy/claims/BatchClaimsTest.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
For #1545: Use SQS batch requests where possible.
- Added `BatchClaims` skeleton
- Added `BatchClaimsTest` which tests how many times `close` method is executed
- Added config file for mocking final classes
- Left todo for `BatchClaims` implementation
=> #1545: Use SQS batch requests where possible.

src/main/groovy/com/zerocracy/stk/pm/cost/funding/recharge_on_deficit.groovy, src/main/groovy/com/zerocracy/stk/pm/cost/funding/recharge_project.groovy, src/test/resources/com/zerocracy/bundles/recharges_on_deficit/_after.groovy, src/test/resources/com/zerocracy/bundles/recharges_on_deficit/_before.groovy, src/test/resources/com/zerocracy/bundles/recharges_on_deficit/claims.xml
#1076: Previously, recharging the project is triggered by `Make payment` and `Ping hourly` claims, which then recharges if the project is under deficit.
I separated the actual recharge into a new claim, `Recharge project`, which is handled by its own stakeholder.  Now the original `recharge_on_deficit` stakeholder checks for deficit only, and generates a _new_ claim (not a copy) to `Recharge project` with a delay of 5 minutes. This should avoid duplicate recharging.
=> #1076 Split recharging into its own claim

src/main/java/com/zerocracy/pmo/Resume.java, src/main/java/com/zerocracy/pmo/Resumes.java, src/test/java/com/zerocracy/pmo/ResumesTest.java
For #1569: Resumes.resume(login) implementation.
- Added `Resume` interface modeling a resume, with `Fake` implementation for tests
- Added `Resumes.resume(login)` method in resume
- Added test for `Resumes.resume(login)` in `ResumesTest`
- Left puzzle for `Resumes.resume(login)`
=> #1569: Resumes.resume(login) implementation.

src/test/java/com/zerocracy/pmo/CatalogTest.java
For #1333: Added board fields to projects on catalog.:
- Added `catalogHasBoardPageInfo` to `CatalogTest` to test if information shown in board page is being stored in `catalog.xml`;
- Added puzzle to finish implementation of `Catalog`, which saves board pages information to `catalog.xml`
=> For #1333: Added board page fields to catalog.

src/test/resources/com/zerocracy/bundles/pays_adviser_on_funding/_after.groovy, src/test/resources/com/zerocracy/bundles/pays_adviser_on_funding/_before.groovy, src/test/resources/com/zerocracy/bundles/pays_adviser_on_funding/claims.xml
For #1536: Implement adviser payment on project funding.
- Added tests for:
- checking if advisor received correct payment on project funding by stripe
- checking if project received correct payment on project funding by stripe
- checking if advisor received correct payment on project funding by donation
- checking if project received correct payment on project funding by donation
=> For #1536: Implement adviser payment on project funding.

src/main/groovy/com/zerocracy/stk/pmo/resumes/assign_examiner.groovy, src/test/resources/com/zerocracy/bundles/deny_resume_application/_after.groovy, src/test/resources/com/zerocracy/bundles/deny_resume_application/_before.groovy, src/test/resources/com/zerocracy/bundles/deny_resume_application/_setup.xml, src/test/resources/com/zerocracy/bundles/deny_resume_application/claims.xml, src/test/resources/com/zerocracy/bundles/deny_resume_application/people.xml
For #1649:
- Added tests for checking if examiner received points for user resume denial, if examiner is not responsible for user resume anymore and if examiner received message.
=> For #1649: Resume denial.

src/main/groovy/com/zerocracy/stk/pm/cost/pay_architect_for_release.groovy, src/main/groovy/com/zerocracy/stk/pm/in/orders/close_job.groovy, src/main/groovy/com/zerocracy/stk/pm/in/orders/notify_declined_job.groovy, src/test/resources/com/zerocracy/bundles/notifies_declined_job/_after.groovy, src/test/resources/com/zerocracy/bundles/notifies_declined_job/_before.groovy, src/test/resources/com/zerocracy/bundles/notifies_declined_job/claims.xml, src/test/resources/com/zerocracy/bundles/notifies_declined_job/people.xml
#1635: Changed `pay_architect_for_release.groovy` to get specific claims instead of only excluding pings, notifys, and errors.
Also added `Job was declined` claim, and added a new stakeholder for that claim to handle notifications (which was previously handled by throwing `SoftException`).
=> #1635 ARC bonus on specific claims only, added "Job was declined" claim

src/main/java/com/zerocracy/farm/sync/MongoDbLock.java, src/test/java/com/zerocracy/farm/sync/MongoDbLockTest.java
For #1644: MongoDB lock implementation.
- Implemented `tryLock()`, `lock()`, `unlock()` and `toString()` in `MongoDbLock`
- Uncommented tests referring these methods in `MongoDbLockTests`
- Left puzzle for creating more tests and complete implementation
=> For #1644: MongoDB lock implementation.

src/main/java/com/zerocracy/tk/TkBoard.java, src/main/resources/xsl/board.xsl, src/test/java/com/zerocracy/tk/TkBoardTest.java
#930: Get all languages from project repos and display them on the board.
Note to reviewer: that the `MkGithub` API returns dummy language values including Java. This is why the unit test works.
Left a puzzle to narrow down display to only the top four ranked languages.
=> #930 Display project languages on Board

src/main/groovy/com/zerocracy/stk/pm/staff/remove_stale_users.groovy, src/test/resources/com/zerocracy/bundles/resigns_stale_users_from_project/_after.groovy, src/test/resources/com/zerocracy/bundles/resigns_stale_users_from_project/_before.groovy, src/test/resources/com/zerocracy/bundles/resigns_stale_users_from_project/claims.xml, src/test/resources/com/zerocracy/bundles/resigns_stale_users_from_project/people.xml, src/test/resources/com/zerocracy/bundles/resigns_stale_users_from_project/roles.xml
#924 Users who are absent from people.xml (deleted/kicked out from Zerocracy) are now deleted from projects.
Exception is users who have `PO` role. Some of our clients are logged in to Zerocracy but are not invited, so they are not counted in `people.xml`. Instead, they are added to projects manually as `PO`. We don't want to kick them out of their own projects, which might possibly become orphaned if they are resigned.
=> #924 Resign users absent from people.xml

src/main/java/com/zerocracy/pm/cost/Ledger.java
#1662: We found the slowdown in `make_payment` is due to `Ledger`, see https://github.com/zerocracy/farm/issues/1662#issuecomment-416454156.
Added a puzzle for migrating to Postgres.
=> #1662 Add puzzle for Ledger Postgres implementation

src/main/groovy/com/zerocracy/stk/pmo/profile/set_rate.groovy, src/main/java/com/zerocracy/claims/ClaimSignature.java, src/test/resources/com/zerocracy/bundles/set_user_rate_eur/_after.groovy, src/test/resources/com/zerocracy/bundles/set_user_rate_eur/_before.groovy, src/test/resources/com/zerocracy/bundles/set_user_rate_eur/_setup.xml, src/test/resources/com/zerocracy/bundles/set_user_rate_eur/claims.xml, src/test/resources/com/zerocracy/bundles/set_user_rate_eur/people.xml
This is for #1282
- The `set_rate` was incorrectly implemented and \1 was used instead of $1 to rewrite "100EUR" into "100 EUR", this resulted in an exception that was never reported back to the user because of #1736.
- Moreover `Cash.S` was expecting a string in the format "EUR 100" and not "100 EUR".
=> Properly parse rate in set_rate command

src/test/java/com/zerocracy/farm/guts/TkGutsTest.java, src/test/java/com/zerocracy/tk/RqWithUser.java, src/test/java/com/zerocracy/tk/TkJoinPostTest.java, src/test/java/com/zerocracy/tk/TkJoinTest.java, src/test/java/com/zerocracy/tk/TkTeamTest.java, src/test/java/com/zerocracy/tk/TkVacanciesTest.java, src/test/java/com/zerocracy/tk/View.java, src/test/java/com/zerocracy/tk/profile/TkAgendaTest.java, src/test/java/com/zerocracy/tk/profile/TkIdentifyTest.java, src/test/java/com/zerocracy/tk/profile/TkProfileTest.java, src/test/java/com/zerocracy/tk/profile/TkUserWbsTest.java, src/test/java/com/zerocracy/tk/project/TkArtifactTest.java, src/test/java/com/zerocracy/tk/project/TkFootprintTest.java, src/test/java/com/zerocracy/tk/project/TkXmlTest.java
#1278: Removed the initialization code in `RqWithUser.make()`. New inner decorator class `RqWithUser.WithInit` created, containing the init code within a `StickyScalar` returning a `RqWithUser`.
Changed test classes to use `RqWithUser.WithInit` where appropriate.
=> #1278 Moved initialization code in RqWithUser to new decorator class

README.md, src/test/java/com/zerocracy/BundlesTest.java
#1308: `BundlesTests` changed to allow specification of exact tests to run via `bundlesTests` system property. Added information in `README.md` to specify how to use this.
=> #1308 Allow running of specific BundlesTests

pom.xml, src/main/java/com/zerocracy/entry/ExtMongo.java
The code addresses the original problem with the downloading failure of MongoDB instance for FreeBSD OS, however, other inconsistencies related to running tests against an existing local MongoDB have been revealed (will create a separate issue for that shortly).
=> 1711: an existing mongodb client configuration for testing provided

src/main/java/com/zerocracy/farm/ruled/RdItem.java, src/test/java/com/zerocracy/farm/ruled/RdItemTest.java
#1728: Delete temp file created by `RdItem` upon close. This should avoid proliferation of orphan temp files.
=> #1728 Delete RdItem temp file after close

pom.xml, src/main/java/com/zerocracy/pmo/ResumeXml.java, src/main/java/com/zerocracy/pmo/Resumes.java, src/main/java/com/zerocracy/tk/TkJoinPost.java, src/test/java/com/zerocracy/pmo/ResumesTest.java
This is for #1645
On top of solving the issue, I had to:
- adapt type of stackoverflow id used everywhere to `long` so that it matches with the type of `Resume.soid()`.
- change existing test and add some more
- increase the max class missed count to account for the unused `Resume.Fake`.
=> Implement Resumes.resume()

src/main/groovy/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy, src/test/resources/com/zerocracy/bundles/dont_elects_and_assigns_performer_when_debt/_after.groovy, src/test/resources/com/zerocracy/bundles/dont_elects_and_assigns_performer_when_debt/_before.groovy, src/test/resources/com/zerocracy/bundles/dont_elects_and_assigns_performer_when_debt/claims.xml, src/test/resources/com/zerocracy/bundles/dont_elects_and_assigns_performer_when_debt/people.xml, src/test/resources/com/zerocracy/bundles/dont_elects_and_assigns_performer_when_debt/roles.xml, src/test/resources/com/zerocracy/bundles/dont_elects_and_assigns_performer_when_debt/wbs.xml, src/test/resources/com/zerocracy/bundles/elects_and_assigns_performer/_after.groovy, src/test/resources/com/zerocracy/bundles/elects_and_assigns_performer_when_debt/_after.groovy, src/test/resources/com/zerocracy/bundles/elects_and_assigns_performer_when_debt/_before.groovy, src/test/resources/com/zerocracy/bundles/elects_and_assigns_performer_when_debt/claims.xml, src/test/resources/com/zerocracy/bundles/elects_and_assigns_performer_when_debt/people.xml, src/test/resources/com/zerocracy/bundles/elects_and_assigns_performer_when_debt/roles.xml, src/test/resources/com/zerocracy/bundles/elects_and_assigns_performer_when_debt/wbs.xml
For #1824:
- Corrected `elect_performer.groovy` to allow job assignment to performer with no rate set when project has no funds
- Added tests to test if 0crat is assigning jobs to users with no rates when project has no funds
- Added test to test if 0crat is not assigning job to user with rate when project has no funds
=> For #1824: Election when project has no funds and performer have no rate

src/main/groovy/com/zerocracy/stk/pmo/profile/invite_friend.groovy, src/main/java/com/zerocracy/pm/staff/GlobalInviters.java, src/test/java/com/zerocracy/pm/staff/GlobalInvitersTest.java, src/test/resources/com/zerocracy/bundles/upO4js_examiner_can_invite/_after.groovy, src/test/resources/com/zerocracy/bundles/upO4js_examiner_can_invite/_before.groovy, src/test/resources/com/zerocracy/bundles/upO4js_examiner_can_invite/claims.xml, src/test/resources/com/zerocracy/bundles/upO4js_examiner_can_invite/people.xml
#1948 - allow pmo users to invite without resume
#1905 - implemented `GlobalInviters` as PMO users and QA in Zerocracy project
=> Allow pmo users to invite without resume

src/main/groovy/com/zerocracy/stk/internal/collect_daily_metrics.groovy, src/main/java/com/zerocracy/pmo/Catalog.java, src/main/java/com/zerocracy/pmo/People.java, src/test/java/com/zerocracy/pmo/CatalogTest.java, src/test/java/com/zerocracy/pmo/PeopleTest.java
#2036 #2035 - new kpi metrics every day:
- `active_projects` - amount of active projects (not on pause)
- `active_users` - amount of users with reputation > 256
- `visible_users` - amount of users with mentor and reputation > 0
- `total_reputation` - total reputation of all visible users
=> New kpi metrics

src/main/groovy/com/zerocracy/stk/pm/in/impediments/add_waiting_label.groovy, src/main/groovy/com/zerocracy/stk/pm/in/impediments/remove_waiting_label.groovy, src/test/resources/com/zerocracy/bundles/upq0fy_adds_waiting_label_to_issue/_after.groovy, src/test/resources/com/zerocracy/bundles/upq0fy_adds_waiting_label_to_issue/_before.groovy, src/test/resources/com/zerocracy/bundles/upq0fy_adds_waiting_label_to_issue/orders.xml
https://github.com/zerocracy/farm/issues/2018
Please note that Reflection is used in BundleTest to mock ExtTelegram.SINGLETON.
=> #2018: Notify performer on wait/continue

src/main/resources/xsl/project.xsl
When I open a project page I see this:
The double period at the end bugs me. It's there in the source:
```html
<p>You are not working in this project, but you can <a href="http://www.zerocracy.com/policy.html#2">apply</a>..
</p>
```
I've removed it. The main closing period of this sentence is further down the XSL, after vesting information.
=> No double period on project page for ousiders

src/main/groovy/com/zerocracy/stk/pm/in/orders/notify_user_on_order.groovy
I receive task notifications:
There is no space between "why" and "you".
I believe now there will be.
I also improved the name of the variable.
=> Improve formatting of task notification for developer

src/main/groovy/com/zerocracy/stk/pm/staff/elections/elect_performer.groovy, src/main/java/com/zerocracy/Xocument.java, src/main/java/com/zerocracy/pm/staff/votes/VsOptionsMaxRevJobs.java, src/main/java/com/zerocracy/pmo/Agenda.java, src/main/java/com/zerocracy/pmo/Options.java, src/test/java/com/zerocracy/pm/staff/votes/VsOptionsMaxRevJobsTest.java, src/test/java/com/zerocracy/pmo/AgendaTest.java
PR for https://github.com/zerocracy/farm/issues/1906.
- Added a `maxRevJobsInAgenda` option to control max REV jobs in agenda. This includes a new `VsOptionsMaxRevJobs` rule and accessor+mutator in `Options` for the new option.
- Added a `String role(job)` method in `Agenda` to determine the role of a job. This was necessary for the `VsOptionsMaxRevJobs` to be able to count REV jobs in the `Agenda`.
- Updated `Xocument`'s version to enable validations against updated XSD in Datum.
=> New maxRevJobsInAgenda option

pom.xml, src/main/groovy/com/zerocracy/stk/pm/comm/notify_in_slack.groovy, src/main/java/com/zerocracy/radars/slack/FkSkSession.java, src/main/java/com/zerocracy/radars/slack/ReInvite.java, src/main/java/com/zerocracy/radars/slack/ReSafe.java, src/main/java/com/zerocracy/radars/slack/RealSkSession.java, src/main/java/com/zerocracy/radars/slack/SkSession.java, src/test/java/com/zerocracy/radars/slack/RealSkSessionTest.java, src/test/resources/com/zerocracy/bundles/upBkMF_notify_in_slack_without_user/_after.groovy, src/test/resources/com/zerocracy/bundles/upBkMF_notify_in_slack_without_user/_before.groovy
This is for #1544 
The main change is that `SkSession` now does not expose the underlying slack lib (which is not OO at all...) so that it is easier to implement a `FkSkSession`.
It also simplifies a bit the usage of `SkSession` in the main code, not only test code.
I've added 2 todos to continue this work and 1 todo to improve the existing test (I have considered that the test was ultimately meant to test `notify_in_slack` when a user exists).
=> #1544 - Improve SkSession interface to implement FkSkSession

src/main/groovy/com/zerocracy/stk/pm/staff/roles/kickout_from_sandbox.groovy, src/test/resources/com/zerocracy/bundles/dont_kickout_graduates_from_sandbox/_after.groovy, src/test/resources/com/zerocracy/bundles/dont_kickout_graduates_from_sandbox/_before.groovy, src/test/resources/com/zerocracy/bundles/dont_kickout_graduates_from_sandbox/claims.xml, src/test/resources/com/zerocracy/bundles/dont_kickout_graduates_from_sandbox/roles.xml
For #2237
- removed `kickout_from_sandbox.groovy` stakeholder
- added test that ensured that user is not banned from sandbox projects if graduated
=> For #2237: Dont kickout graduates from sandbox projects
